### ISSUE TITLE
Could not connect to ms azure instance mongodb

### ISSUE THREAD

**Issue by Slavenin** [elixir-mongo/mongodb#106]
Hi! 
I try connect to ms azure instance mongodb
```
config :app, MongoRepo,
  adapter: Mongo.Ecto,
  database: "cache",
  username: "cache",
  password: "***",
  hostname: "***",
  port: ***,
  ssl: true
```
but throws exception:
>15:58:21.258 [error] Mongo.Protocol (#PID<0.340.0>) failed to connect: ** (Mongo.Error) ssl connect: TLS connection is closed - :closed

**Comment by ericmj** [comment]
Looks like the SSL connection failed. The error doesn't tell us much what went wrong unfortunately. Does Azure require certificates?

**Comment by Slavenin** [comment]
I don`t know. Db settings in azure not contain certificates parameters

**Comment by ericmj** [comment]
SSL works in our tests and it works locally. Unfortunately I can't debug this as I don't have access to Azure and from the error message I cannot give more feedback.

**Comment by Slavenin** [comment]
Lib has debug mode?

**Comment by michalmuskala** [comment]
It is my understanding, that debug mode on the client side wouldn't help much since the error is originating from the database side - the connection is closed abruptly by the database server.
