### ISSUE TITLE
Mongo.delete_* naming

### ISSUE THREAD

**Issue by rockerBOO** [elixir-mongo/mongodb#11]
Was writing some more documentation and noticed naming of "remove" from Mongo is named as "delete_*". The main Mongo API uses `remove()`, so I was looking for that in the code. Connection is using remove though, so not sure why its like this. Could just be something that's going to change later.

Summary: Why is `Mongo` using `delete_*` instead of `remove`?

**Comment by ericmj** [comment]
The specification Mongo provides for driver implementors say that the names `deleteOne` and `deleteMany` should be used.

https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#id18

**Comment by rockerBOO** [comment]
Interesting, maybe they are moving to `delete` from remove. They have almost identical functionality, yet have no mention of each other in the documentation except that remove uses delete. 

Thanks for the clarification :sweat_smile:

**Comment by ericmj** [comment]
I think most drivers use `delete` but some have aliases from `remove` to `delete`. The node driver is aliasing, the ruby driver only provides `delete`, the python driver is doing partial aliasing, the c# driver only does `delete`.

The official mongo docs use the shell for example code. You will have to ask 10gen why the shell driver doesn't follow their own guidelines :).
