### ISSUE TITLE
invalid document containing atom and string keys

### ISSUE THREAD

**Issue by xnagpa** [elixir-mongo/mongodb#112]
Hello! 
I faced a weird behavior while executing this:
Mongo.find(:mongo, "my_collection",%{}, sort: ["modified_at": -1], modifiers: ["hint": "my_index_name"]) |> Enum.to_list

I keep getting this:
** (ArgumentError) invalid document containing atom and string keys: [{"$query", []}, {"$orderby", [modified_at: -1]}, {:hint, "labels_slug_type"}]

I don't know why, but it changes my "$hint"'s type to atom
how to specify modifiers correctly?

**Comment by michalmuskala** [comment]
```
["hint": "my_index_name"]
```
hint is an atom here, the `"":` form is equivalent to `:""` - the special atom syntax.

**Comment by xnagpa** [comment]
Got it! 
@michalmuskala  So the correct way is %{"hint"=>  "my_index_string_name"} or maybe %{"hint" => %{_id: 1}}?

**Comment by xnagpa** [comment]
Found it a minute ago. So the correct way to use modifiers is: 
modifiers: %{"$hint" => "my_index", "$explain" => 1})
Thank you for your collaboration!
