### ISSUE TITLE
How do I validate Unique Constraint?

### ISSUE THREAD

**Issue by hariharasudhan94** [elixir-mongo/mongodb#113]
My Model looks like this

defmodule myApp.Department do
  use myApp.Web, :model

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "departs"  do
    field :name, :string
    field :shortDescription, :string
    field :aboutDepartment, :string
  end

  def changeset(struct, params \\%{}) do
    struct
    |> cast(params, [:name, :shortDescription, :aboutGroup])
    |> validate_required([:name, :shortDescription],[message: "Group Name Must Not Be Em"])
    |>unique_constraint(:name)
  end

end

Controller Code Like follow

def create(conn, %{"department" => depart_params}) do
   changeset = Department.changeset(%Department{}, depart_params)
    if changeset_group.valid? do
         Mongo.insert_one(:mongo, "departs", changeset.changes)
         json conn, "ok"
    else
        json conn, "not ok"
   end
end

according to docs unique constraints can perform only on insertion , so how can i validate and pattern  match the error like follow

case insert(changeset) do
      {:ok, _depart_params} ->
        conn
        |>json("ok")
      {:error, changeset} ->
        render conn, "new.html", changeset: %{changeset | action: :insert}
    end

**Comment by ericmj** [comment]
This is an ecto [1] question or mongodb_ecto [2] question, but I think constraints are not supported.

[1] https://github.com/elixir-ecto/ecto
[2] https://github.com/michalmuskala/mongodb_ecto

**Comment by hariharasudhan94** [comment]
Instead of Using 

> mongodb_ecto 

i am directly using mongodb_driver by following this [https://tomjoro.github.io/2017-02-09-ecto3-mongodb-phoenix/](link)  but i am not sure how to check name which  already exists  in collection while inserting.   

>Changeset  has function called  [https://hexdocs.pm/ecto/Ecto.Changeset.html#unique_constraint/3](function)  which checks constraint on insertion if not throw exception so that i can pattern match and redirect to different route

**Comment by ericmj** [comment]
No, it's not possible without using the mongo/ecto adapter or building it yourself unfortunately.

**Comment by hariharasudhan94** [comment]
Ok,using mongodb/ecto currently not supporting ecto2/3 that's why i used ericmj/mongodb driver dicrectly to app

**Comment by ericmj** [comment]
You can try this PR: https://github.com/michalmuskala/mongodb_ecto/pull/84
