### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by CharlesIrvineKC** [elixir-mongo/mongodb#114]
Since there is no documentation, I assume that if you know Mongo already, then you will know how to use this library. Is that true? Are there pointers of any kind that you can provide to a new Mongo user that would help me use your library? -Thanks

**Comment by aymanosman** [comment]
There are official getting started guides in a variety of languages https://docs.mongodb.com/manual/#getting-started, if that helps.

Also docs for this library can be found here https://hexdocs.pm/mongodb/Mongo.html#content.

**Comment by CharlesIrvineKC** [comment]
The hexdocs pointer is very helpful. Also, I should have thought of it before I opened the issue - your test cases are the perfect documentation. Thanks!
