### ISSUE TITLE
Problems trying to use command!/3

### ISSUE THREAD

**Issue by Charlyzzz** [elixir-mongo/mongodb#115]
Hi there!

I'm having troubles trying to create an index ([reference](https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/#db.collection.createIndex), just in case)

~~~elixir
{:ok, db} = Mongo.start_link(database: "test")
Mongo.command(db, [createIndex: "names", keys: %{a: 1}, opts: %{}])

> ** (Mongo.Error) command failed: no such command: 'createIndex', bad cmd: '{ createIndex: "names", keys: { a: 1 }, opts: {} }' 59
~~~

Any ideas about what I'm missing?
Thanks!

Erwin

**Comment by michalmuskala** [comment]
`createIndex` is not a command - it's a method in the mongo shell. The index of commands is located here: https://docs.mongodb.com/manual/reference/command/

In particular there's [`createIndexes`](https://docs.mongodb.com/manual/reference/command/createIndexes/#dbcmd.createIndexes) command:

```elixir
index = %{key: %{a: 1}, name: "name", opt1: value1, ...}
Mongo.command(db, [createIndexes: "collection", indexes: [index]])
```
