### ISSUE TITLE
Unable to complete handshake with Mongo Atlas

### ISSUE THREAD

**Issue by christianjgreen** [elixir-mongo/mongodb#117]
We've recently migrated from compose.io to mongo atlas clusters. (https://www.mongodb.com/cloud/atlas)

When attempting to connect to the primary node in the cluster a ssl connection error is thrown:
```
[error] Mongo.Protocol (#PID<0.979.0>) failed to connect: ** (Mongo.Error) ssl connect: TLS Alert: handshake failure - {:tls_alert, 'handshake failure'}
[error] SSL: :certify: tls_connection.erl:619:Fatal error: handshake failure - malformed_handshake
```

We are able to connect to the node via other clients with the same credentials. The cluster only supports replica sets, however we presumed we could at least connect to the primary node with this driver without any issues.

**Comment by christianjgreen** [comment]
This has been resolved with OTP release 19.3. Will be closing!
Checkout the comment thread of #95 for more details

**Comment by andrewsheelan** [comment]
@Arthien  We are trying to implement Mongo Atlas as well. Would it be possible to share connection code snippets, please. We have been receiving the following error:
Mongo.Protocol (#PID<0.303.0>) failed to connect: ** (Mongo.Error) tcp connect: connection refused - :econnrefused 

Here's the connection start_link we are using:
conn = Mongo.start_link(
  database: "admin", 
  seeds: [
    "server-shard-01:27017",
    "server-shard-02:27017",
    "server-shard-03:27017"
  ], 
  set_name: "test-shard-0", 
  username: "myuser", 
  password: "mypassword", 
  auth_source: "admin", 
  port: 27017, 
  type: "replica_set_primary", 
  ssl: true 
) 

Would be great if you can help with this. Thanks.

**Comment by ankhers** [comment]
@andrewsheelan This issue is unrelated to yours. This was because of a bug with erlang's SSL module. You can read more about the issue [in the erlang mailing list](http://erlang.org/pipermail/erlang-questions/2016-December/091181.html) where I asked for help in trying to figure out the issue.

Please create a new issue with a full stack trace of the error you are receiving.
