### ISSUE TITLE
Remove BSON.DateTime and replace with DateTime

### ISSUE THREAD

**Issue by lau** [elixir-mongo/mongodb#121]
This issue is for discussing removing `BSON.DateTime` and replacing it with `DateTime`.

Creating this issue so that https://github.com/ericmj/mongodb/pull/120 discussion can be about just the PR to add functions for native Elixir`DateTime` structs without removing `BSON.DateTime.`

**Comment by michalmuskala** [comment]
I'm definitely :+1: on removing the `BSON.DateTime`, I don't think it's needed especially that we have the native structs now.

On the other hand, the current struct just holds the integer, for the new structs there's the additional step of decoding the value, which is more expensive, but I'm not sure it will actually matter.
