### ISSUE TITLE
Issue with BSON.encode and Mongo.aggregate

### ISSUE THREAD

**Issue by kodburn** [elixir-mongo/mongodb#122]
Hi, I have an problem with aggregating a collection using `Mongo.aggregate`. To do that I have to encode the pipeline into BSON document. 

Here's the pipeline:
```
pipeline = [
    %{
      "$project" => %{
        player_id: 1,
        game_id: 1,
        sessions_id: 1
      }
    }, %{
      "$group" => %{
        _id: "$game_id",
        customer_ids: %{ "$push" => "$customer_id" },
        versions: %{ "$push" => "$versions" }
      }
    }
  ]
```
Next, I encode it: 
```
bson_pipeline = Mongo.Encoder.encode(pipeline)
```
Everything works fine by now, but then when I aggregate:
```
cursor = Mongo.aggregate(MongoPool, "versions", bson_pipeline)
Enum.to_list(cursor)
```
I get an error:
```
no case clause matching: {:ok, %Mongo.ReadResult{cursor_id: 0, docs: [%{"code" => 15942, "errmsg" => "pipeline element 0 is not an object", "ok" => 0.0}], from: 0, num: 1}}
```
When we decode our bson_pipeline we can see what caused the error:
```
BSON.decode(bson_pipeline)
# => 
%{"0" => %{"$project" => %{"game_id" => 1, "player_id" => 1,
      "sessions_id" => 1}},
  "1" => %{"$group" => %{"_id" => "$game_id",
      "customer_ids" => %{"$push" => "$customer_id"},
      "versions" => %{"$push" => "$versions"}}}}
```
So, Mongo wants the pipeline to be an array of objects, like in this example: But BSON.encode produces a map like %{"0" => ..., "1" => ...}
```
db.orders.aggregate([
                     { $match: { status: "A" } },
                     { $group: { _id: "$cust_id", total: { $sum: "$amount" } } },
                     { $sort: { total: -1 } }
                   ])
``` 
But BSON.encode produces a map like %{"0" => ..., "1" => ...}

Is there any way to solve this? To forse BSON.encode to create a bson array of objects?
Thank You

**Comment by ericmj** [comment]
This seems to work correctly for me when trying the encode and decode functions:

```
iex(1)> pipeline = [
...(1)>     %{
...(1)>       "$project" => %{
...(1)>         player_id: 1,
...(1)>         game_id: 1,
...(1)>         sessions_id: 1
...(1)>       }
...(1)>     }, %{
...(1)>       "$group" => %{
...(1)>         _id: "$game_id",
...(1)>         customer_ids: %{ "$push" => "$customer_id" },
...(1)>         versions: %{ "$push" => "$versions" }
...(1)>       }
...(1)>     }
...(1)>   ]
[%{"$project" => %{game_id: 1, player_id: 1, sessions_id: 1}},
 %{"$group" => %{_id: "$game_id", customer_ids: %{"$push" => "$customer_id"},
     versions: %{"$push" => "$versions"}}}]
iex(2)> %{x: pipeline} |> BSON.encode |> BSON.decode
%{"x" => [%{"$project" => %{"game_id" => 1, "player_id" => 1,
       "sessions_id" => 1}},
   %{"$group" => %{"_id" => "$game_id",
       "customer_ids" => %{"$push" => "$customer_id"},
       "versions" => %{"$push" => "$versions"}}}]}
```

What is the `Mongo.Encoder.encode` function you are using, it is not part of this project?

**Comment by kodburn** [comment]
`Mongo.Encoder.encode` is a part of the project, but when I was trying `BSON.encode([:some, :list])` I was getting `no function clause matching in BSON.encode/1` error, so I tried `BSON.Encoder.encode([:some, :list])` then, which seemed to work, but incorrectly, as I found out later. 
  I didn't know I have to do `%{x: [:some, :list]} |> BSON.encode`, instead of `[:some, :list] |> BSON.encode` to encode list into BSON array.
  Ok, and now to perform Mongo.aggregate I still have to pass it BSON, which should be an array, not a map like `{x: [list]}`. How do I do that?
  ps. Sorry if the questions are stupid, I'm new Elixir :)

**Comment by ericmj** [comment]
`Mongo.aggregate` expects an elixir list for the pipeline argument, you shouldn't BSON encode it first. What error do you get when running `Mongo.aggregate(MongoPool, "versions", pipeline)` when `pipeline` is an unencoded elixir list?

**Comment by kodburn** [comment]
Yes, it works now. The documentation confused me, and I thought I have to encrypt pipeline to BSON before passing it to aggregate function. Would be nice, if there would be some examples of using the aggregation.
Thank You

**Comment by ericmj** [comment]
> Yes, it works now. The documentation confused me, and I thought I have to encrypt pipeline to BSON before passing it to aggregate function. Would be nice, if there would be some examples of using the aggregation.

Contributions are always welcome. Glad it worked for you.
