### ISSUE TITLE
Issue w/ dotted property names

### ISSUE THREAD

**Issue by raif-s-naffah** [elixir-mongo/mongodb#123]
when trying to store the following instance

    "context" => %{ ...,
      "extensions" => %{"http://id.example.com/extension/attempt-id" => "foo"}, 
      ... }

i get

    %Mongo.Error{code: 57, message: "command failed: The dotted field 'http://id.example.com/extension/attempt-id' in 'context.extensions.http://id.example.com/extension/attempt-id' is not valid for storage."}

if this is a known issue, is there a work-around?

**Comment by ankhers** [comment]
Mongo does not support [keys with a dot](https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names). Unfortunately, there is not really a standard work around for this as different people have different needs.

**Comment by raif-s-naffah** [comment]
i was just about to update this issue w/ that link, but you were faster!

understood + thanks for the prompt reply.
