### ISSUE TITLE
Why remove find() opts from find_one()?

### ISSUE THREAD

**Issue by austinsmorris** [elixir-mongo/mongodb#128]
https://github.com/ericmj/mongodb/blob/master/lib/mongo.ex#L396

This recently bit me during a refactoring.  Why remove the sort/order_by opts from `find_one()` when it is just a proxy to `find()`?  Without explicitly warning the user, it seems like it would be better to either honor the opts or `raise` if they are present.

Thoughts?  I'd be happy to submit a PR if a change is desired.

**Comment by ericmj** [comment]
If you need sort/order_by you should use `find` and with `limit: 1`.

**Comment by ericmj** [comment]
The official driver does the same thing: https://docs.mongodb.com/manual/reference/method/db.collection.findOne/
