### ISSUE TITLE
insert_many crash on blank document set

### ISSUE THREAD

**Issue by rockerBOO** [elixir-mongo/mongodb#13]
If you are just recursion processing results, and pass a blank result set, it crashes on this. 

``` elixir
** (FunctionClauseError) no function clause matching in Mongo.many_docs/1
             (mongodb) lib/mongo.ex:449: Mongo.many_docs([])
             (mongodb) lib/mongo.ex:130: Mongo.insert_many/4
    (twitch_discovery) lib/index/stream.ex:2: TwitchDiscovery.Index.Stream.mongo_save_many/1
    (twitch_discovery) lib/index/stream.ex:2: TwitchDiscovery.Index.Stream.get_next/1
    (twitch_discovery) lib/index.ex:41: TwitchDiscovery.Index.index/0
```

**Comment by ericmj** [comment]
The protocol does not allow us to insert zero documents. I guess we can fake it, send nothing and return a fake response?

**Comment by rockerBOO** [comment]
Just having it output an error would be fine with me, just crashes completely right now.

**Comment by ericmj** [comment]
We are raising a FunctionClauseError here which is comparable to an ArgumentError. I think raising an error is better than returning an error here. The error message can be better though.

**Comment by ericmj** [comment]
The official Node driver also errors:

```
> db.collection('coll').insertMany([])
MongoError: insert must contain at least one document
```

**Comment by rockerBOO** [comment]
I guess I was expecting a %Mongo.Error{}?

**Comment by ericmj** [comment]
Functions that return `{:ok, _} | {:error, _}` usually still raise when the input values are bad.

**Comment by rockerBOO** [comment]
If there is an argument error, and it should still raise an error when the input values are bad, then it should remain the same error. I am not sure how the best way to make these issues findable when people run into them. Custom errors can have hints on what to do to fix it though.

Thanks for letting me peak into your mind on these issues. :smile:

**Comment by ericmj** [comment]
This will raise an ArgumentError with a more informative error message.
