### ISSUE TITLE
Readme update for 0.4.0?

### ISSUE THREAD

**Issue by lau** [elixir-mongo/mongodb#132]
Hi @ankhers 

Is the readme up to date for 0.4.0? Specifically these parts: https://github.com/ankhers/mongodb#usage and  https://github.com/ankhers/mongodb#connection-pooling ?

**Comment by ankhers** [comment]
As far as I can tell, everything there is still correct. However, it should be updated to mention the different options to use replica sets. I will add that sometime this week.

**Comment by ankhers** [comment]
I just updated the readme with some information about replica sets. Let me know if you think there still needs to be an improvement.
