### ISSUE TITLE
Error with 0.4

### ISSUE THREAD

**Issue by elie222** [elixir-mongo/mongodb#136]
We just upgraded to version 0.4 of this package to use the replicaSet support, but we've been having issues with it. On startup we get this error:
```
** (EXIT) time out
    (elixir) lib/gen_server.ex:737: GenServer.call/3
    (mongodb) lib/mongo/monitor.ex:71: Mongo.Monitor.check/1
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Any idea what the error could be? This is a MongoDB instance that is also connected to a Meteor app.

**Comment by ankhers** [comment]
There have been a couple reports lately of people saying that this driver does not seem to work on MongoDB instances created by Meteor. I am not sure of the reason behind this. 

Someone else is actively looking into the issue, and I hope to find some time this weekend to look into it a bit myself.

**Comment by ankhers** [comment]
And as I posted this, @ben-ic may have found the issue. Are you by chance running multiple Mongo instances, or is this just a single server that is configured as a replica set?

**Comment by ben-ic** [comment]
This issue is happening when you try to connect to Meteors bundled Mongodb.  Something with how they have configured the database prevents the package from auto detecting the correct topology type

A work around for now is to add the type to your mongodb configuration in Elixir
`type: :single`

**Comment by wangbus** [comment]
This was a problem with not specifying the `seeds` key in the configuration while doing `start_link`

Not a bug. Please close.

Hello @ben-ic and @elie222!
