### ISSUE TITLE
Pools of pools

### ISSUE THREAD

**Issue by mjheilmann** [elixir-mongo/mongodb#138]
I am using mongodb with poolboy for multiple projects.  When using :observer to explore the application tree during a benchmarking session, I found that I am getting multiple poolboy pools.

Mongo.Topology is creating a Mongo.Monitor and a poolboy connection pool.  But it creates this pair for each node connection, and the Mongo.Monitor has its own poolboy pool.  On a single node with poolboy set to 5, it is making 10 connections to the database.  If I set pool_size to 20, I make 40 connections to the database.  So on a mongo replication cluster with 3 nodes and poolboy set to 20, I end up with 6 connection pools of 20 each, and 120 connections to my cluster.

Am I missing something?  I am expecting a single pool of the configured number of connections to be created and used for queries.

This is tested with :mongodb 0.4.0, and with :poolboy 1.5.1 and occurs both when using seeds against multiple endpoints, and when connecting to a single url with no clustering.  I can view the pools and connections using :observer, but the connection count is confirmed from mongo.

**Comment by ankhers** [comment]
I believe this is a mistake in the replica set implementation. I will have to double check the mongo docs, but I believe it is only supposed to create a single connection in the monitor, and not a pool.

I am a little tied up with other things at the moment, but I will look into this within the next week or two.

**Comment by christianjgreen** [comment]
Confirmed that its effecting my production project as well. Multiple pools. 👍

**Comment by mjheilmann** [comment]
I hacked a fix in my code that may be correct, but could use more eyes.

```
lib/mongo/monitor.ex
 @@ -31,6 +31,7 @@ defmodule Mongo.Monitor do
    def init([server_description, topology_pid, heartbeat_frequency_ms, connection_opts]) do
      opts = # monitors don't authenticate and use the "admin" database
        connection_opts
 +      |> Keyword.drop([:pool])
        |> Keyword.put(:database, "admin")
        |> Keyword.put(:skip_auth, true)
      {:ok, pid} = DBConnection.start_link(Mongo.Protocol, opts)
```

The module creates a pool per connected mongodb node, but it no longer creates pools for monitors.  Connections cut in half.

**Comment by ankhers** [comment]
Would you be able to throw that into a PR?
