### ISSUE TITLE
can not connect when using a cname

### ISSUE THREAD

**Issue by svsdehh** [elixir-mongo/mongodb#139]
When using a cname to connect to the mongodb it is not working as expected. When using the real server name it is working as it should. But using cnames to connect to a mongodb is the recommended way.

It seems, that the driver recognizes the correct server, as in hosts, me and primary is the correct server name set. but nevertheless I get the following error:

** (exit) exited in: GenServer.call(:mongo, :topology, 5000)
    ** (EXIT) time out
[error] GenServer #PID<0.556.0> terminating
** (stop) exited in: GenServer.call(#PID<0.555.0>, {:server_description, %{address: "cname_to_mongo_db:27017", arbiters: [], election_id: #BSON.ObjectId<595d9545177574f9c47fda70>, error: nil, hosts: ["real_server_name:27017"], last_update_time: -576460749789, last_write_date: #<DateTime(2017-07-07T05:10:58.000Z Etc/UTC)>, max_wire_version: 5, me: "real_server_name:27017", min_wire_version: 0, op_time: %{"t" => -1, "ts" => #BSON.Timestamp<6439892251593146369>}, passives: [], primary: "real_server_name:27017", round_trip_time: 36, set_name: "replicaset_name", set_version: 11, tag_set: %{"dc" => "NOHAM"}, type: :rs_primary}}, 30000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:737: GenServer.call/3
    (mongodb) lib/mongo/monitor.ex:71: Mongo.Monitor.check/1
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

and as said, when using the real server name and not the cname in the connection string everything is working as expected.

**Comment by ankhers** [comment]
Thanks for pointing this out. I will take a look into what the issue is.

**Comment by cystbear** [comment]
👍 
same issue for me

**Comment by ankhers** [comment]
I found the issue for this. The short of it is:

* Pid A (Mongo.Monitor) sends a message to Pid B (Mongo.Topology)
* Pid B tries to stop Pid A
* Pid A is still waiting for a response from Pid B and does not stop

I'm not entirely sure how to fix it at the moment. Maybe @chowevtfy can chime in?

**Comment by svsdehh** [comment]
thanks for fixing this. it is now working as expected with cnames!  thats great!

:+1:
