### ISSUE TITLE
(ArgumentError) argument error ... :erlang.send(Mongo.Events, {:notify, %Mongo.Events.TopologyOpeningEvent{topology_pid: #PID<0.307.0>}})

### ISSUE THREAD

**Issue by seeekr** [elixir-mongo/mongodb#146]
Hi there,

new to this whole ecosystem, needed a way to talk to mongodb from Elixir, found this project. Tried instructions from README.md (adding :mongodb to mix.exs applications, and to deps as well), then getting this error that's not helpful at all for a newcomer:

```
** (EXIT from #PID<0.73.0>) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.send(Mongo.Events, {:notify, %Mongo.Events.TopologyOpeningEvent{topology_pid: #PID<0.307.0>}})
        (elixir) lib/gen_event.ex:534: GenEvent.notify/2
        lib/mongo/topology.ex:70: Mongo.Topology.init/1
        (stdlib) gen_server.erl:365: :gen_server.init_it/2
        (stdlib) gen_server.erl:333: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Poked around some code a bit, but can't really figure out what is wrong. Using it like this:

```
{:ok, conn} = Mongo.start_link(database: "test")
```

Mongo is up and running, test-db is created. Not sure what else to check. Any help would be appreciated.

Cheers,
Denis

**Comment by ankhers** [comment]
What version of Elixir and OTP are you using?

**Comment by seeekr** [comment]
Latest of both. (Edit: Mac OS X 10.11)

```
$ elixir -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.5
```

**Comment by ankhers** [comment]
Unfortunately I do not know what is going on here. There is no reason that should fail. Does this happen to you every time, or did it only happen once?

How did you install erlang and elixir?

**Comment by ericmj** [comment]
The process name `Mongo.Events` is not registered. Can you show your `mix.exs` and how you start the application?

**Comment by seeekr** [comment]
@ankhers Happens every time. On a coworker's machine (Windows) as well as on mine (Mac). We may be copy-pasting the same (erroneous) stuff or something, I don't know :)

For me, I installed erlang and elixir via homebrew.

@ericmj Interesting! I think you're on to something when asking about how we start the application -- because when I do `mix phoenix.server` then no error happens. But what I'm trying to do (sorry for not mentioning it, didn't realize it could matter) is run a custom mix task. What we're attempting to do in the app is write a script that imports stuff from a MongoDB into a MySQL instance, so we don't really need Mongo at server runtime, but rather when a one-off script runs. Is that possible? I'm sorry I don't have a clear understanding yet of Elixir's / OTPs "applications", how it starts and manages stuff...

```elixir
defmodule Mix.Tasks.Mongo do
  def run(_) do
    {_, _conn} = Mongo.start_link(hostname: "localhost")
  end
end
```

**Comment by ankhers** [comment]
Because that is a mix task, you are going to have to manually start the application. Just add `Application.ensure_all_started(:mongodb)` before your `Mongo.start_link/1` line.

**Comment by seeekr** [comment]
Thanks! Not a bug, so closing.

**Comment by seeekr** [comment]
I would leave a tip for your support here, but was unable to find the project on Gratipay. Anywhere else I can leave a small monetary "thank you" note?

**Comment by ankhers** [comment]
I appreciate the thought, but I do not have anything setup to receive payments for any of the projects that I work on, nor do I intend to at the moment.

**Comment by seeekr** [comment]
That's cool, just wanted to offer :) Cheers, thanks for your work!
