### ISSUE TITLE
Mongo.Monitor.check/1

### ISSUE THREAD

**Issue by mikepc** [elixir-mongo/mongodb#148]
I'm trying to connect to a replica set with credentials, but I'm having an issue.

The connection returns no error, and a PID. 
When I do anything with that PID, the process hangs and eventually times out.

The debug information coming out of the timeout error is reporting that it's connecting to the admin database even though I've specified the database as such:

`
        {:ok, pid} = Mongo.start_link(
                                      database: "bizdata",
                                      username: Application.get_env(:padimport, :mongouser ),
                                      password: Application.get_env(:padimport, :mongopass),
                                      seeds: ["db.0.url.com:10279", "db.1.url.com:10279"]
                                      )
`

**Comment by mikepc** [comment]
I've tried the direct connection as well:
database: "bizdata",
                                      username: Application.get_env(:padimport, :mongouser ),
                                      password: Application.get_env(:padimport, :mongopass),
                                      hostname: "db.0.url.com",
                                      port: 10279,

With the same results.

**Comment by mikepc** [comment]
Connecting to my local database without authentication works peachy.

**Comment by ankhers** [comment]
Connecting to the admin database is expected. We do this in order to monitor that the server is up and running and to do various communications unrelated to your application (e.g., when an election happens). This is fairly standard across Mongo drivers.

Unfortunately you have not given a lot of information here in order for me to diagnose the problem. Seeing the actual stack trace would be a good start. However, would you mind testing the master branch of this driver? If I am right, your issue has already been fixed.

**Comment by mikepc** [comment]
22:45:08.942 [error] GenServer #PID<0.431.0> terminating
** (stop) exited in: GenServer.call(#PID<0.430.0>, {:server_description, %{address: "alcatraz.0.mongolayer.com:10279", arbiters: [], election_id: nil, error: nil, hosts: ["c279.alcatraz.0.mongolayer.com:10279", "c279.alcatraz.1.mongolayer.com:10279"], last_update_time: -576460443865, last_write_date: nil, max_wire_version: 2, me: "c279.alcatraz.0.mongolayer.com:10279", min_wire_version: 0, op_time: nil, passives: [], primary: "c279.alcatraz.1.mongolayer.com:10279", round_trip_time: 207, set_name: "set-565c04e5a9a18b346b00074a", set_version: 4, tag_set: %{}, type: :rs_secondary}}, 30000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:774: GenServer.call/3
    (mongodb) lib/mongo/monitor.ex:71: Mongo.Monitor.check/1
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :check}
State: %{connection_pid: #PID<0.432.0>, heartbeat_frequency_ms: 10000, opts: [skip_auth: true, database: "admin", pool: DBConnection.Connection, username: "<nope>", password: "<nope>", hostname: "alcatraz.0.mongolayer.com", port: 10279], server_description: %{address: "alcatraz.0.mongolayer.com:10279", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}, topology_pid: #PID<0.430.0>}

**Comment by mikepc** [comment]
The above error appears after about 1 minute of waiting for an insert command.

**Comment by mikepc** [comment]
I figured out I'm defining the port twice. Damn. <3 thanks man!
