### ISSUE TITLE
Connection pooling Mongo.aggregate/4 UndefinedFunctionError

### ISSUE THREAD

**Issue by serhiimelnik** [elixir-mongo/mongodb#149]
- Connection pool in application supervisor
`worker(Mongo, [[name: :mongo, seeds: ["localhost:27017"], set_name: "local", type: :single, database: "test", pool: DBConnection.Poolboy]])`

- Request
`Mongo.aggregate(:mongo, "test", [], pool: DBConnection.Poolboy) |> Enum.to_list`

- Result
```
** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
    :invalid_message.exception([])
    (db_connection) lib/db_connection.ex:926: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1133: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
    (mongodb) lib/mongo.ex:142: Mongo.aggregate/4
```

**Comment by ankhers** [comment]
Thanks for reporting this. I just release v0.4.1 with a fix for this and a couple other things. Give it a go and let me know if you have any other issues.

**Comment by serhiimelnik** [comment]
Thanks. After update this works.
