### ISSUE TITLE
Can't sort on sub fields

### ISSUE THREAD

**Issue by rockerBOO** [elixir-mongo/mongodb#15]
Sort is made with atoms, and can't do this with them. I think they should remain as a string keys.

``` elixir
Mongo.find(MongoPool, %{}, [sort: [game.name: -1]])
```

Thanks :smiley:

**Comment by rockerBOO** [comment]
Sorry, apparently its designed to work with atoms or binary separately. The following works.

``` elixir
Mongo.find(MongoPool, %{}, [sort: %{"game.name" => -1]])
```

**Comment by michalmuskala** [comment]
You can also use the syntax for atoms with special characters:

``` elixir
Mongo.find(MongoPool, %{}, [sort: ["game.name": -1]])
```

That's because `:atom` is equivalent to `:"atom"`.
