### ISSUE TITLE
Documentation is Missing

### ISSUE THREAD

**Issue by mikepc** [elixir-mongo/mongodb#151]
As a new user to elixir, with a dependency on mongodb, it would be really nice to have some example queries provided to show folks how to use the driver, complete with using "$in", "$and", and "$or" conditions.  Sending users to the mongodb documentation is officially correct, but doesn't  really show users how to use the driver.

**Comment by mlovic** [comment]
You can find an API reference at https://hexdocs.pm/mongodb/api-reference.html#content. I don't think it will have any examples of Mongo queries though, as that API should be not depend on the driver at all.

Incidentally, I couldn't find that link to the documentation anywhere in the README. Perhaps it should be included? Either there or in the repo description?
