### ISSUE TITLE
Error starting simple application during connect phase

### ISSUE THREAD

**Issue by justmark** [elixir-mongo/mongodb#152]
Hi,

I have a 3 member Mongo replica set (v3.4.7).  Linux I'm using is Ubuntu 16.04 LTS (fully patched).  When I set up a simple Elixir project to connect to this instance get the following error:

```
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.send(Mongo.Events, {:notify, %Mongo.Events.TopologyOpeningEvent{topology_pid: #PID<0.145.0>}})
        (elixir) lib/gen_event.ex:221: GenEvent.notify/2
        lib/mongo/topology.ex:70: Mongo.Topology.init/1
        (stdlib) gen_server.erl:365: :gen_server.init_it/2
        (stdlib) gen_server.erl:333: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Elixir Version:

```
elixir --version
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1
```

Deps:

```
Running dependency resolution...
Dependency resolution completed:
  connection 1.0.4
  db_connection 1.1.2
  mongodb 0.4.1
  poolboy 1.5.1
All dependencies up to date
```

The connect statement I'm using:

```
{:ok, conn} = Mongo.start_link( database: "db", seeds: ["ip1:27017", "ip2:27017", "ip3:27017"], username: "user", password: "pass", auth_source: "auth_db", pool: DBConnection.Poolboy )
```

I have checked to make sure that I can connect to Mongo through the Mongo client from this machine.  I've checked all the iptables configurations as well.

**Comment by ankhers** [comment]
Is this by chance happening in a mix task?

**Comment by ankhers** [comment]
I think this is a duplicate of #146. Can you verify?

**Comment by justmark** [comment]
Hi, 

It isn't a mix task.  I just stepped away from my office.  I'll get you more information shortly.

Mark

**Comment by justmark** [comment]
Closing - was an issue with the escript configuration.  Now that I've resolved that, it is attempting connections as expected.  Thanks for the prompt reply!
