### ISSUE TITLE
cursor not found on replica set

### ISSUE THREAD

**Issue by mjheilmann** [elixir-mongo/mongodb#153]
When executing a large (100k results) query against a replica set, the driver will raise "cursor not found".  This is using the :secondary_preferred read preference.  If I set the preference to :primary (default) the behavior goes away.  Small queries are not affected by this.  I rewrote the query as an aggregate to reduce the result size, but the pipeline is slow, and causes a different error (usually a timeout).

I suspect that when we are batching large results from a replica set, the driver is switching nodes between calls to get_more, and loses the cursor.

**Comment by ankhers** [comment]
Thanks for finding this. I will look into a fix.

**Comment by christianjgreen** [comment]
<3

**Comment by christianjgreen** [comment]
@ankhers Could this be it? Taking in a random node instead of the last node the query was executed on?
https://github.com/ankhers/mongodb/blob/master/lib/mongo.ex#L722

**Comment by christianjgreen** [comment]
It looks like the topology PID is being passed around correctly, but on replica sets that PID can reference any of the nodes so the actual node PID is lost.

**Comment by ankhers** [comment]
Partially. There are three cursor functions found in the `Mongo` module. I
believe it is `singly_cursor`, `aggregation_cursor` and something else (I'm
not at my computer right now). Those functions are currently taking the
topology PID, but they should be taking the `conn`.

Then there is `get_more`, `kill_cursor` and I believe one more. They are
currently written to expect the topology PID and are calling that select
server function. But once you pass in the connection directly to the
cursor, you can skip that step.

I have been out of town for the past few days so I have been unable to fix
this. I will be getting home tonight, so I can probably fix it within the
next couple days.

**Comment by christianjgreen** [comment]
Thanks!
