### ISSUE TITLE
timeout in topology gen_server

### ISSUE THREAD

**Issue by cristianberneanu** [elixir-mongo/mongodb#159]
There seems to be a deadlock or race condition in the topology gen_server. When running unit tests, I sometimes get this crash because of timeout:

```
12:42:59.795 [error] GenServer #PID<0.909.0> terminating
** (stop) exited in: GenServer.call(#PID<0.907.0>, {:server_description, %{address: "localhost:27017", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: -576460746283, last_write_date: nil, max_wire_version: 5, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: 3, set_name: nil, set_version: nil, tag_set: %{}, type: :standalone}}, 30000)
    ** (EXIT) time out
Last message: []
```

**Comment by ankhers** [comment]
I just ran the test suite 50 times on a loop. I didn't see a single failure against current master.

Can you give me a little more information about your setup? What version of Elixir, Erlang and mongo are you using? how often are you seeing this failure (1 in 5 runs)? What ref are you on?

Is it a single test that keeps failing, or is it random?

**Comment by cristianberneanu** [comment]
Thanks for looking into this.

I am using the latest version from hex, `0.4.3`.
I see the failure in 1 from 10-15 runs. The test that fails is random.

```
mongod --version
db version v3.4.8
git version: 8ef456f89f63ab12941fe6b5352b20cff2522da3
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
allocator: tcmalloc
modules: none
build environment:
    distmod: debian71
    distarch: x86_64
    target_arch: x86_64
```
```
iex -v
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:8:4] [async-threads:10] [hipe] [kernel-poll:false]

IEx 1.4.0
```

I will try to create a simple project somewhere that will reliably reproduce the issue.
BTW, I am creating and destroying a new connection for each test in my suite.

**Comment by ankhers** [comment]
Alright. I think I misunderstood your original question. Are you seeing this behaviour in your own applications test suite, or in this repositories test suite?

**Comment by cristianberneanu** [comment]
Sorry for not being clear on this.

I am seeing the issue in my applications's test suite. Unfortunately, the application and tests are somewhat complex and I can't easily extract a reproducible case.

**Comment by cristianberneanu** [comment]
I tried to write a test case that reproduces the error, but without success until I lowered the `@min_heartbeat_frequency_ms` and `@heartbeat_frequency_ms` settings. This makes some sense, as the tests I was running took a long time and put a heavy load on the system, so I assume the deadlock only happens when the system is stressed.

I managed to reproduce the issue by using these steps:

1. In `monitor.ex`, set `@min_heartbeat_frequency_ms 100`.
2. In `topology.ex`, set `@heartbeat_frequency_ms 100`.
3. Add a new test file with the following content:
```
defmodule Mongo.QueryTest do
  use MongoTest.Case, async: true

  @collection "query_test"
  @records 10000
  @timeout :timer.seconds(30)
  @parameters hostname: "localhost", database: "mongodb_test"

  setup_all do
    {:ok, pid} = Mongo.start_link(@parameters)
    for i <- 1..@records, do:
      {:ok, _} = Mongo.insert_one(pid, @collection, %{name: "name#{i}", value: i}, [])
    :ok = GenServer.stop(pid)
  end

  for index <- 1..100 do
    test "query test #{index}" do
      assert div(@records * (@records + 1), 2) = sum_values()
    end
  end

  defp connect!() do
    self = self()
    parameters = @parameters ++ [types: true, sync_connect: true, timeout: @timeout,
      pool: DBConnection.Connection, pool_timeout: @timeout, after_connect: fn (_) -> send self, :connected end]
    {:ok, pid} = Mongo.start_link(parameters)
    receive do
      :connected -> pid
    after :timer.seconds(5)
      ->
        GenServer.stop(pid)
        raise "Unknown failure during database connection process!"
    end
  end

  defp sum_values() do
    pid = connect!()
    options = [max_time: @timeout, timeout: @timeout, pool_timeout: @timeout, batch_size: 100, allow_disk_use: true]
    sum =
      pid
      |> Mongo.aggregate(@collection, [], options)
      |> Stream.map(& &1["value"])
      |> Enum.sum()
    GenServer.stop(pid)
    sum
  end
end
```
4. Execute the tests.

Hope this helps.

**Comment by ankhers** [comment]
https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#heartbeatfrequencyms

`@heartbeat_frequency_ms` - This should be configurable, but that appears to have been missed when doing the initial replica set implementation. This should be easily fixed.

`@min_heartbeat_frequency_ms` - This should always be set to 500.

As for the tests in your previous comment that you wrote. Assuming that is representative of what your applications test suite is doing, why are you starting and stopping so many connections to the database? Why not just start it and use it for the test instead of starting a new connection for each test?

**Comment by cristianberneanu** [comment]
I am not saying that the default values for those settings should be changed. I originally got the timeout exception when using the default values, so the bug will happen in that case as well, only less often. The reduced settings are only needed to reproduce the issue reliably.

Regarding connection setup:
The application I am working on is pretty complex. It has an abstraction layer for executing queries over different types of back-ends: PostgreSQL, MySQL, SQL Server, MongoDB and so on. The executed queries and the post-processing of results are very complex and usually take a very long time.
Pooling connections would not help with performance, as the bottleneck is somewhere else.
The library version we currently use (`0.2.1`) works fine with this setup. I encountered the error when I tried to update to the latest version.

**Comment by cristianberneanu** [comment]
I had some more time to investigate this further and, if my understanding of the code is correct, it seems to me that the source of the problem is the circular dependency between `Topology` and `Monitor`.

When stopped, the `Topology` process tries to also stop all `Monitor` processes that reference it.
But those processes could be stuck in a `check/1` call that tries to call the `Topology` process back.
Because both calls are synchronous, a deadlock occurs.

One solution to this would be to make the `:server_description` notification asynchronous (change it from `call` to `cast`). From my tests, this change seems to fix the issue, but my limited understanding of the code prevents me to be sure somethings else won't break because of it.

**Comment by ankhers** [comment]
I apologize for the delay in any sort of resolution on this. I will (hopefully) be looking into this over the next couple weeks. I believe I have found a way to reproduce this.

**Comment by jfcloutier** [comment]
My application does intensive ETL and, every 3-4 days, all DB operations fail because of: {:noproc, {GenServer, :call, [#PID<0.2729.0>, :topology, 5000]}}. I am using what is currently the lastest commit to master ("65bd68adbc2753c38d927ad0ba804fe8e66d50d7").
Are there any workarounds? Thanks.

**Comment by etroynov** [comment]
Hi, same problem :(

application.ex
```
defmodule Api.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the endpoint when the application starts
      supervisor(ApiWeb.Endpoint, []),
      # Start your own worker by calling: Api.Worker.start_link(arg1, arg2, arg3)
      # worker(Api.Worker, [arg1, arg2, arg3]),
      worker(Mongo, [[name: :mongo, database: "ti", pool: DBConnection.Poolboy]])
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Api.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ApiWeb.Endpoint.config_change(changed, removed)
    :ok
  end

  defimpl Poison.Encoder, for: BSON.ObjectId do
    def encode(id, options) do
      BSON.ObjectId.encode!(id) |> Poison.Encoder.encode(options)
    end
  end
end
```

Controller:
```
  def index(conn, _params) do
    cursor = Mongo.find(:mongo, "teams", %{}, limit: 20, pool: DBConnection.Poolboy)

    teams = cursor |> Enum.to_list()

    render conn, "index.json", teams: teams
  end
```

Error:
```
[error] #PID<0.468.0> running ApiWeb.Endpoint (cowboy_protocol) terminated
Server: localhost:4000 (http)
Request: GET /v1/teams
** (exit) exited in: GenServer.call(:mongo, :topology, 5000)
    ** (EXIT) time out
```

**Comment by astutecat** [comment]
I also have the same problem here - the code and errors I have are equivalent to the context you already have here. Looking forward to seeing a solution soon!

**Comment by baquiax** [comment]
It happens to me with versions greater than `0.5.0`, I downgrade my version to `0.4.7` and it works fine. I only happened to me when ran my tests =(

**Comment by rblack** [comment]
@baquiax Looks like your issue is unrelated to this bug. I believe you use `pool: DBConnection.Poolboy`, but with 0.5.0 you probably should use only `pool_size` option, because new version uses `DBConnection.ConnectionPool` by default (fix me if I'm wrong here).

**Comment by deadtrickster** [comment]
hello, I have this too:


```
{pool,'Elixir.DBConnection.Poolboy'}]) at <0.986.0> exit with reason {timeout,{'Elixir.GenServer',call,[<0.986.0>,{server_description,#{address => <<"localhost:27017">>,arbiters => [],election_id => nil,error => nil,hosts => [],last_update_time => -576460624031,last_write_date => nil,max_wire_version => 7,me => nil,min_wire_version => 0,op_time => nil,passives => [],primary => nil,round_trip_time => 4,set_name => nil,set_version => nil,tag_set => #{},type => standalone}},30000]}} in context child_terminated
```

mongo logs:

```
2019-06-11T14:46:11.888+0200 I NETWORK  [conn81] end connection 127.0.0.1:49927 (2 connections now open)
2019-06-11T14:46:11.889+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:33407 #82 (3 connections now open)
2019-06-11T14:46:41.891+0200 I NETWORK  [conn82] end connection 127.0.0.1:33407 (2 connections now open)
2019-06-11T14:46:41.892+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:34715 #83 (3 connections now open)
2019-06-11T14:47:11.896+0200 I NETWORK  [conn83] end connection 127.0.0.1:34715 (2 connections now open)
2019-06-11T14:47:11.897+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:55075 #84 (3 connections now open)
2019-06-11T14:47:41.899+0200 I NETWORK  [conn84] end connection 127.0.0.1:55075 (2 connections now open)
2019-06-11T14:47:41.900+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:37461 #85 (3 connections now open)
2019-06-11T14:48:11.904+0200 I NETWORK  [conn85] end connection 127.0.0.1:37461 (2 connections now open)
2019-06-11T14:48:11.906+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:44961 #86 (3 connections now open)
2019-06-11T14:48:40.917+0200 I NETWORK  [conn86] end connection 127.0.0.1:44961 (2 connections now open)
2019-06-11T14:48:40.917+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:41709 #87 (3 connections now open)
2019-06-11T14:49:10.920+0200 I NETWORK  [conn87] end connection 127.0.0.1:41709 (2 connections now open)
2019-06-11T14:49:10.920+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:53971 #88 (3 connections now open)
```
and this is what I get from update_one:

```
{:error, :selection_timeout}
```

**Comment by ankhers** [comment]
@deadtrickster Which version of this driver are you currently using? If you are not using 0.5.1, could you please update to it and see if you are still having issues?

**Comment by deadtrickster** [comment]
I just started with 

```
{:mongodb, ">= 0.0.0"},
{:poolboy, ">= 0.0.0"}
```

can't look at mix.lock now but I guess it's the most recent one.

**Comment by ankhers** [comment]
I assumed you were using an older version because of the reference to Poolboy. The `db_connection` library no longer uses it, so you can remove the `:pool` option from your configs. That may be your issue.

**Comment by deadtrickster** [comment]
Hey, this helped, thanks. No idea where I got that pool:. Maybe old blog post.

**Comment by ankhers** [comment]
I'm going to close this issue as it seems to have been fixed with moving to 0.5.x. If anyone is still having this issue on 0.5.x+, please open a new issue.

**Comment by novaugust** [comment]
I'm getting this in 0.5.1, not in tests but just running the app. Every thirty seconds, a crash & timeout:
```
11:45:15.379 [error] GenServer #PID<0.856.0> terminating
** (stop) exited in: GenServer.call(#PID<0.854.0>, {:server_description, 
  %{address: "x", arbiters: ["x"], election_id: #BSON.ObjectId<7fffffff0000000000000009>, error: nil, hosts: ["x", "x"], last_update_time: -576460657032, 
    last_write_date: ~U[2019-07-31 18:44:39.000Z], max_wire_version: 6, me: "x", min_wire_version: 0, op_time: %{"t" => 9, "ts" => #BSON.Timestamp<1564598679:1>}, 
    passives: [], primary: "x", round_trip_time: 186, set_name: "x", set_version: 21, tag_set: %{}, type: :rs_primary
}}, 30000)
    ** (EXIT) time out
Last message: []
```

**Comment by novaugust** [comment]
> please open a new issue.

whoops, will do
