### ISSUE TITLE
Multi - db support vs nil database option

### ISSUE THREAD

**Issue by rhetzler** [elixir-mongo/mongodb#161]
In 0.3 and earlier, passing [database: nil] as an opt resulted in the default database for the connection to be used, as if no database option had been set at all.

In 0.4+ such a parameter will trip an exception as the nil is not replaced by the default value and makes it's way down to the message encoding level where it dies, eg:
```elixir
     ** (ArgumentError) argument error
     stacktrace:
       :erlang.iolist_size([<<0, 0, 0, 0>>, [nil, 46 | "sample"], <<0, 1, 0, 0, 0>>, [<<15, 0, 0, 0>>, ["", 2, ["id", 0], [<<2, 0, 0, 0>>, "a", 0]], 0], [<<34, 0, 0, 0>>, ["", 3, ["$set", 0], [<<23, 0, 0, 0>>, [["", 2, ["b", 0], [<<2, 0, 0, 0>>, "b", 0]], 2, ["c", 0], [<<2, 0, 0, 0>>, "c", 0]], 0]], 0]])
       (mongodb) lib/mongo/messages.ex:60: Mongo.Messages.encode/2
```

Do we want to maintain backwards compatibility with the nil -> default behaviour, or catch it earlier with a more intuitive error/warning?

**Comment by ankhers** [comment]
When you are passing this in as an option, are you doing this in a `Mongo.find/4` or something? Because when I use `Mongo.start_link(database: nil)`, I get a crash immediately.

**Comment by rhetzler** [comment]
you're right, my example isn't very clear, and yes, it's for Mongo.find any anything that accepts database name in it's options after mongo has already started.

Scenario is that mongo is booted with a "meta" db for a multi-tenant app (each tenant gets it's own logically separate db), so app switches to customer's db via database: parameter. using nil here (before i upgraded to 0.4) defaulted to the meta db for some administrative functionality. This is just as easily accomplished by not passing the parameter at all. The question was mostly whether nil should fall back to default?; is this either desirable or should be considered a bug. If a bug, we can just close this.

**Comment by ankhers** [comment]
I would prefer to be explicit in which database you are attempting to query. So I would consider `nil` pointing to the default database to be a bug.
