### ISSUE TITLE
Mongo.child_spec/2 returns data in deprecated format

### ISSUE THREAD

**Issue by georgysavva** [elixir-mongo/mongodb#167]
I was trying to override Mongo child_spec:
`Supervisor.child_spec(Mongo, id: {Mongo, 1})`

And it caused an error, because Supervisor expects child_spec as a map, and Mongo returns as a tuple:

`
** (BadMapError) expected a map, got: {Mongo, {Mongo, :start_link, [[]]}, :permanent, 5000, :worker, [Mongo]}
        (stdlib) :maps.put(:id, {Voting.Foo, 1}, {Mongo, {Mongo, :start_link, [[]]}, :permanent, 5000, :worker, [Mongo]})
        (elixir) lib/supervisor.ex:703: anonymous fn/2 in Supervisor.child_spec/2
        (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
        (voting) lib/voting/supervisor.ex:40: Voting.Supervisor.init/1
        (stdlib) supervisor.erl:294: :supervisor.init/1
        (stdlib) gen_server.erl:365: :gen_server.init_it/2
        (stdlib) gen_server.erl:333: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
`

I assume this is happening because of the Supervisor.Spec.worker/3 call inside the Mongo.child_spec/2 function. 
I am new in Elixir, maybe i am wrong. Thank you)

**Comment by ankhers** [comment]
Maps as child specs are supported from Elixir 1.5. This project currently aims to work with Elixir `~> 1.3` (see the `mix.exs` file). Until we drop support for < 1.5, we will continue to use it. If a new version of Elixir drops support for it and we need to support < 1.5, we can do some kind of version checks. However, I do not think that is currently necessary.
