### ISSUE TITLE
Publish to Hex

### ISSUE THREAD

**Issue by optikfluffel** [elixir-mongo/mongodb#17]
This would be pretty cool. They also have [a nice guide for it](https://hex.pm/docs/publish).

**Comment by ericmj** [comment]
It will be published to Hex as soon as everything is properly documented.

**Comment by optikfluffel** [comment]
Yay!
![Yay](http://www.reactiongifs.com/r/yaay.gif)

**Comment by optikfluffel** [comment]
Is this released now or did you just close it? I can't find anything but [mongo](https://hex.pm/packages/mongo) on hex.

**Comment by ericmj** [comment]
It will be released today.

**Comment by optikfluffel** [comment]
Thank, sorry for being impatient :)
