### ISSUE TITLE
Support for 3.6

### ISSUE THREAD

**Issue by tominkozhimala** [elixir-mongo/mongodb#171]
Will support for MongoDB 3.6 be added? 

I'm seeing the following error with the latest release:
`Mongo.Protocol (#PID<...>) failed to connect: ** (Mongo.Error) tcp connect: connection refused - :econnrefused`

Not seeing this issue when using 3.4

My assumption is that this is a compatibility issue with localhost binding
https://docs.mongodb.com/manual/release-notes/3.6-compatibility/#bind-ip-compatibility

**Comment by ankhers** [comment]
I have a PR started that will track the changes required to get this adapter working with Mongo 3.6.

**Comment by rawkode** [comment]
Hey @tominkozhimala, I am using this adapter with mongoDB 3.6 and have no problems. If you're running mongoDB with Docker, you just need to modify the container command:

```
  mongodb:
    image: mongo:3.6
    command: mongod --bind_ip_all --replSet replSet --storageEngine wiredTiger
```

**Comment by vgunawan** [comment]
Hi @ankhers, any ETA when the 3.6 branch will be ready/merged as master? Our mongo is about to be upgraded to 3.6 and we need to ensure that our app is running with it.

@rawkode, to your response above, did you use the 3.6 branch or master?

Thanks all

**Comment by ankhers** [comment]
Everything seems to be working with 3.6. The tests passed on Travis, but
are failing for some reason locally for me. I also do all of my development
on 3.6 currently and I have not run into any issues.

I unfortunately have not had the time to look into the reason for the
failure I am seeing. I'm going to look it shortly.

**Comment by vgunawan** [comment]
Thank you @ankhers, I will begin testing soon with 3.6. If anything I will bring it up here, and sure I can create some PRs if need be.
