### ISSUE TITLE
Auto-detect topology type

### ISSUE THREAD

**Issue by sauvainr** [elixir-mongo/mongodb#176]
Currently the topology needs to be known in advance and set with the option:
```[type: :replica_set_no_primary]```

In most situations the development database will be standalone, the integration/staging a replicaset & production a sharded cluster.

The application then need to defines this options in it's configuration management or environment  variable.

It would be great not to worry about it.

**Comment by ankhers** [comment]
Have you actually tested that it is required? The `Mongo.Topology` module should try and figure it out if you do not include the initial type in the configuration.

**Comment by sauvainr** [comment]
I encountered some errors. I will try to provide more details.

**Comment by sauvainr** [comment]
@ankhers here the error situation:
Connect to a replicaset with url ```'mongodb://db1:27017,db2:27017/dbname?replicaSet=set-name'```
 using ```type: :unknown``` I get: ```{:error, :set_name_bad_topology}```

**Comment by ankhers** [comment]
Thanks for this. I will look into it.

**Comment by ankhers** [comment]
Can you please test #187 and let me know if it fixes your problem?

**Comment by sauvainr** [comment]
@ankhers  looks working for my case thanks

**Comment by sauvainr** [comment]
@ankhers  any plan to tag a new release soon?

**Comment by ankhers** [comment]
I am going to see if I can get a couple more issues sorted out first.
