### ISSUE TITLE
Fails to use currentDate

### ISSUE THREAD

**Issue by rawkode** [elixir-mongo/mongodb#177]
Hey,

I've got the following code that works:

```elixir
    Mongo.update_one(
      :mongo,
      "events",
      %{"identifier": document.identifier, "serial_number": document.serial_number},
      %{"$set": document},
      [pool: DBConnection.Poolboy, upsert: true])
```

The problem occurs when I expand to:

```elixir
    Mongo.update_one(
      :mongo,
      "events",
      %{"identifier": document.identifier, "serial_number": document.serial_number},
      %{"$currentDate": %{datetime: %{"$type": "timestamp"}}, "$set": document}},
      [pool: DBConnection.Poolboy, upsert: true])
```

This doesn't work - I can't find anything in the documentation that would suggest how we use `$currentDate`

**Comment by ankhers** [comment]
Can you give some more detail about what doesn't work? Are you getting an error? Is the document just not updating correctly?

I just tested it to verify that it works, and it seems to be working on my machine.

**Comment by rawkode** [comment]
Sorry @ankhers, I believe this was my own mistake. Though, I am having problems getting the read after write to work consistently. I've passed `j: true` and `w: :majority` in through multiple methods:

`Mongo.start_link([name: :mongo, seeds: ["mongo:27017"], database: "events", pool: DBConnection.Poolboy, w: :majority, j: true])`

and

`Mongo.insert_one(:mongo, "events", document, [pool: DBConnection.Poolboy, j: true, w: :majority])`

Neither seem to work for me, though the documentation on this hasn't been touched in 2 years and there seems to have been a move to `db_connection` since then, would this affect that?

**Comment by ankhers** [comment]
Would you please be able to create a new ticket for that? Just to make it more searchable for anyone else in the future.

**Comment by rawkode** [comment]
No problem, @ankhers. Thanks for your prompt responses, appreciated 👍
