### ISSUE TITLE
Cannot get a connection after successful Mongo start

### ISSUE THREAD

**Issue by georgysavva** [elixir-mongo/mongodb#182]
I have a worker server that launches immediately after the Mongo launches by the same supervisor, and starts querying the Mongo:
`
children=[
  {Mongo, [name: :mongo, database: "test", pool: DBConnection.Poolboy]},
  {MyWorker, []}
]
`
The problem is that calls to the Mongo returns :error, without any additional info. I found out that this :error comes from Topology.connection_for_address because the connection pool is empty.
I assume it happens because the Mongo did't have enough time to establish the connections. When i add Process.sleep(1000) in my worker startup, i don't see such errors. What is the best way to eliminate my problem? I think this issue is somehow connected to #158

**Comment by ankhers** [comment]
That does sound like the same issue. When #158 gets fixed and if you are still having trouble, please feel free to re-open this ticket.
