### ISSUE TITLE
Running the equivalent of ObjectId(_id).getTimestamp()

### ISSUE THREAD

**Issue by SirajKakeh** [elixir-mongo/mongodb#193]
Hello! 
I've searched every where before asking here. In Mongo shell I can run `ObjectId(_id).getTimestamp()` and get the creation time of a document with id `_id`.
I was wondering if there was an equivalent for this command in this driver. I've seen the function `Mongo.command` but no matter what combination I try to use it I don't seem to find the correct way!

**Comment by ankhers** [comment]
We don't have a prebaked function for that. However, you should be able to do something along the lines of

``` elixir
iex(1)> %BSON.ObjectId{value: value} = Mongo.object_id
#BSON.ObjectId<5a808c75b3acd912f7b62f4d>
iex(2)> << secs :: unsigned-big-32, _rest :: binary >> = value
<<90, 128, 140, 117, 179, 172, 217, 18, 247, 182, 47, 77>>
iex(3)> DateTime.from_unix!(secs)
%DateTime{calendar: Calendar.ISO, day: 11, hour: 18, microsecond: {0, 0},
 minute: 33, month: 2, second: 25, std_offset: 0, time_zone: "Etc/UTC",
 utc_offset: 0, year: 2018, zone_abbr: "UTC"}
```

If you would like to submit a PR with this functionality, I would gladly merge it.
