### ISSUE TITLE
SSL TCP connect timeout error

### ISSUE THREAD

**Issue by ghost** [elixir-mongo/mongodb#203]
Please can have have a varriable instead of a hard-coded value for, ssl connections?

lib/monogo/protocol.ex:86

```
case :ssl.connect(sock, ssl_opts, 5000) do #hard coded connection time out
```

It was a pain in the ass to debug. But this basically stop us from connecting to our atlas database.

Can we pass a global from start_link?

Would something like:

```
case :ssl.connect(sock, ssl_opts, @ssl_timeout) do
```
be acceptable?

**Comment by michalmuskala** [comment]
Looking at current master, it seems like this is already an option:

https://github.com/ankhers/mongodb/blob/2a111b09597a5a5879f040e6f1c5c4d702e99a35/lib/mongo/protocol.ex#L89

**Comment by ghost** [comment]
Can we actually release a version then that has this?

**Comment by ankhers** [comment]
I will release a new version shortly.

**Comment by ankhers** [comment]
Sorry for the delay. But I just release v0.4.6.

**Comment by ghost** [comment]
Thanks!

**Comment by ankhers** [comment]
Just as a heads up, when I release 0.5.0, the `:connect_timeout_ms` option will be called `:connect_timeout`

**Comment by jschorr** [comment]
Can anyone please tell me what the various options for ssl_opts can be?  I have a Production replica set that uses the following in /etc/mongod.conf: ``  ssl:
    mode: requireSSL
    PEMKeyFile: /etc/ssl/mongodb.pem
    CAFile: /etc/ssl/ca.pem
    clusterFile: /etc/ssl/mongodb.pem 
    disabledProtocols: TLS1_0,TLS1_1``
