### ISSUE TITLE
Connecting using a UNIX Domain Socket

### ISSUE THREAD

**Issue by ankhers** [elixir-mongo/mongodb#207]
@Fudoshiki asked in ankhers/mongodb_ecto#154 how we could use the driver to connect to a socket.

**Comment by ankhers** [comment]
In short there is no way to currently connect to a socket.

The simplest thing we could do is use `:hostname` as `{:local, "/tmp/mongodb-27017.sock"}`. But it would be nice to have a slightly better experience around that. Maybe introduce a new `:socket` key that takes the path to the socket and wraps it for us?

**Comment by Fudoshiki** [comment]
https://github.com/elixir-ecto/postgrex/blob/ad6310e860165358798b842e5b36e24a4f2aaf3f/CHANGELOG.md used `:socket ` key

https://stackoverflow.com/questions/36961692/how-do-i-configure-phoenix-to-use-sockets-with-postgresql
