### ISSUE TITLE
List Collections

### ISSUE THREAD

**Issue by caldempsey** [elixir-mongo/mongodb#211]
No functionality yet implemented to list collections. As advised this is something I will be looking into this weekend.

**Comment by ankhers** [comment]
The [specification](https://github.com/mongodb/specifications/blob/f4bb783627e7ed5c4095c5554d35287956ef8970/source/enumerate-collections.rst) may help a lot here. Feel free to ping me if you have any questions.

You will also want to check the wire version, if it is less than 3, then you will do [this](https://github.com/mongodb/specifications/blob/f4bb783627e7ed5c4095c5554d35287956ef8970/source/enumerate-collections.rst#pre-mongodb-276-versions) section. If it is greater than or equal to 3, you will do [this](https://github.com/mongodb/specifications/blob/f4bb783627e7ed5c4095c5554d35287956ef8970/source/enumerate-collections.rst#post-mongodb-280-rc3-versions) section. You should be able to find an example of how to check the wireversion in the code.

**Comment by ankhers** [comment]
[This](https://github.com/mongodb/mongo/blob/master/src/mongo/db/wire_version.h) list of wire versions may also come in handy.

**Comment by ankhers** [comment]
This was merged in #240
