### ISSUE TITLE
update_one with $pull

### ISSUE THREAD

**Issue by Lazarus404** [elixir-mongo/mongodb#212]
So, I'm migrating from comtihon/mongodb-erlang to this driver, as the former doesn't support proper aggregate batching.  However, while the transfer is mostly seemless, I have found an issue.

Given the following:
```
    update_statement = %{"$pull" => %{"address_book" => %{"id" => address_id}}}
    result = Utils.Mongo.update_one(MongoPool, @collection, filter, update_statement)
  
    case result do
      {:ok, %Mongo.UpdateResult{matched_count: 0}} ->
        {:error, %{reason: "Not Found"}}

      {:ok, %Mongo.UpdateResult{matched_count: 1, modified_count: 0}} ->
        {:error, %{reason: "Address not found"}}

      {:ok, %Mongo.UpdateResult{matched_count: 1, modified_count: 1} = result} ->
        :ok
```
If I pass an address id that doesn't exist, I would expect it to return `{:error, "Address not found"}` and for the address_book array to remain unchanged.  This is how it works in mongodb-erlang. However, with this library, while the address_book is indeed unchanged, I'm receiving the `:ok` as the UpdateResult object has `modified_count` set to 1.

**Comment by ankhers** [comment]
I am not seeing the same behaviour.

I have the following information in my collection

```
Mongo.find(pid, "bar", %{}) |> Enum.to_list
[%{"_id" => #BSON.ObjectId<5b465928b3acd90167bb1027>,
   "list" => [%{"a" => 1}, %{"a" => 1}, %{"a" => 2}, %{"a" => 3}]}]
```

I then use the following

```
update_statement = %{"$pull" => %{list: %{a: 4}}}
Mongo.update_one(pid, "bar", %{"_id" => 12}, update_statement)
%Mongo.UpdateResult{matched_count: 0, modified_count: 0, upserted_id: nil}}
```

When I instead pass an empty filter to the update, which will match everything, I am getting the matched and modified counts

```
Mongo.update_one(pid, "bar", %{}, update_statement)
{:ok,
 %Mongo.UpdateResult{matched_count: 1, modified_count: 1, upserted_id: nil}}
```

**Comment by Lazarus404** [comment]
Oh, no, you missed the issue.  Perform the same with a valid match in the document but no match in the $pull.  So:

```
Mongo.find(pid, "bar", %{}) |> Enum.to_list
[%{"_id" => #BSON.ObjectId<5b465928b3acd90167bb1027>,
   "list" => [%{"a" => 1}, %{"a" => 1}, %{"a" => 2}, %{"a" => 3}]}]
update_statement = %{"$pull" => %{list: %{a: 4}}}
Mongo.update_one(pid, "bar", %{"_id" => #BSON.ObjectId<5b465928b3acd90167bb1027>}, update_statement)
%Mongo.UpdateResult{matched_count: 1, modified_count: 1}}
```
It should be
```
%Mongo.UpdateResult{matched_count: 1, modified_count: 0}}
```

**Comment by Lazarus404** [comment]
The point is that the document is found (`matched_count: 1`), but no data was updated (`modified_count: 0`)

**Comment by ankhers** [comment]
Oh okay. I see the issue now. It appears that we are still using the opcodes for unawknowledged writes. We should be using commands for awknowledged writes. A little more information can be found [here](https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/#request-opcodes).

**Comment by ankhers** [comment]
I am actually going to close this ticket because the current functionality does technically follow the spec. But I will make another in order to update to the newer commands.
