### ISSUE TITLE
Replace :milliseconds with :millisecond

### ISSUE THREAD

**Issue by ben-pr-p** [elixir-mongo/mongodb#218]
On Elixir 1.8.0-dev, I'm getting the folllowing warning:

```
warning: deprecated time unit: :milliseconds. A time unit should be :second, :millisecond, :microsecond, :nanosecond, or a positive integer
  (elixir) lib/system.ex:898: System.warn/2
  (elixir) lib/system.ex:752: System.convert_time_unit/3
  (elixir) lib/calendar/iso.ex:544: Calendar.ISO.from_unix/2
  (elixir) lib/calendar/datetime.ex:119: DateTime.from_unix/3
  (elixir) lib/calendar/datetime.ex:167: DateTime.from_unix!/3
  (mongodb) lib/bson/decoder.ex:71: BSON.Decoder.type/2
  (mongodb) lib/bson/decoder.ex:134: BSON.Decoder.doc_fields/2
  (mongodb) lib/bson/decoder.ex:129: BSON.Decoder.document/1
  (mongodb) lib/bson/decoder.ex:15: BSON.Decoder.documents/2
  (mongodb) lib/mongo/protocol/utils.ex:22: Mongo.Protocol.Utils.command/3
  (mongodb) lib/mongo/protocol.ex:121: Mongo.Protocol.wire_version/1
  (mongodb) lib/mongo/protocol.ex:313: Mongo.Protocol.ping/1
  (db_connection) lib/db_connection/connection.ex:373: DBConnection.Connection.handle_info/2
  (connection) lib/connection.ex:810: Connection.handle_async/3
  (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
  (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
  (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Seems like we just need to replace :millisecond with :millisecond here: https://github.com/ankhers/mongodb/search?q=%3Amilliseconds&unscoped_q=%3Amilliseconds, right?

**Comment by ankhers** [comment]
Sounds right.

**Comment by ankhers** [comment]
Just fixed in master

**Comment by ankhers** [comment]
Fixed too soon. Only 1.6+ supports it. Will need to replace at a later date.

**Comment by diogo-ribeiro-bitmaker** [comment]
@ankhers Hey! is this in your roadmap for anytime soon? i'm using your _mongodb_ecto_ and everytime I run the tests or the server it shows like 6 warnings, not only for milliseconds but for :microseconds and :seconds as well.
Thanks in advance! :)

**Comment by ankhers** [comment]
Like I said in my previous comment, I can't do this until we use a minimum version of 1.6 because it is not supported in anything earlier.

**Comment by emaiax** [comment]
Hello @ankhers. I also use `mongodb_ecto` and since Elixir 1.8 is out, isn't a good idea to bump the version to at least 1.6? Thanks!

**Comment by ankhers** [comment]
I try to keep my Elixir version in line with what the ecto team is doing. And as of right now, they are still targeting Elixir 1.4, just like this driver.

**Comment by ankhers** [comment]
This has just been fixed in master.

**Comment by diogo-ribeiro-bitmaker** [comment]
@ankhers is it possible to bump the mongodb_ecto version of mongodb to 0.4.7? (it's in 0.4.2) Thanks!

**Comment by ankhers** [comment]
@diogo-ribeiro-bitmaker That is not necessary. The mongodb_ecto package is not relying specifically on 0.4.2. It is set to work with any of the 0.4.x series. You should just be able to run `mix deps.update mongodb_ecto` and it should update all of the dependencies of the mongodb_ecto package. Keep in mind this specific ticket has not been released.
