### ISSUE TITLE
Setting a field equal to a function evaluation?

### ISSUE THREAD

**Issue by vans163** [elixir-mongo/mongodb#22]
Say I have an incremental id, in elixir i set "_id"=> "incrId()",   "timest"=>"db.eval(\"Date()\")"

```
            Mongo.insert_one(MongoPool, "test", %{
                    "_id"=> "incrId()",
                    "timest"=> "db.eval(\"Date()\")"
                })
```

This makes the record saved without evaluating the function.Neither way works. Using the commandline for mongo this behavior does not happen as the functions get evaluated as they are inserted.

**Comment by ericmj** [comment]
It seems it is only possible to execute javascript with the `$where` operator and in `mapReduce`, source: http://docs.mongodb.org/master/core/server-side-javascript/.

Do you have examples of other drivers (except for the shell) that has this functionality?

**Comment by vans163** [comment]
Thats probably right. Seems the way to do it is:
%{"retval"=> nextId} = Mongo.run_command(MongoPool, %{"eval"=> "return nextId()"})

But another question. Its documented to use lastModified and set a timestamp to do this:
http://docs.mongodb.org/manual/reference/operator/update/currentDate/

$currentDate: { lastModified: true, "fieldtimestamp": { $type: "timestamp"} }

It also documents you can set a field to: new Date() to get the current datetime which obv does not work doing "new Date()" as the field value.

What would the equivalent in the library be?  

EDIT: It seems that the best way to get the behavior I need is to write mongodb js functions for everything and call them using run_command.

**Comment by ericmj** [comment]
> It also documents you can set a field to: new Date() to get the current datetime which obv does not work doing "new Date()" as the field value.

It's not documented on the page you linked, can you link to it?

> EDIT: It seems that the best way to get the behavior I need is to write mongodb js functions for everything and call them using run_command.

You can easily get the current time in Elixir.

**Comment by vans163** [comment]
An example is:

```
db.system.js.save({
    _id: "insertHit",
    value: function(ip_addr) {
        var nextId = db.eval("nextId()");

        db.hit.insert(
        {
            _id: nextId,
            ip: ip_addr,

            datestamp: new Date(),
            lastModified: new Date()
        })

        return nextId;
    }
})

db.system.js.save({
    _id: "updateHitParam",
    value: function(id, param) {
    db.hit.update( 
        { _id: id },
        {
            $currentDate: { lastModified: true },
            $set: {
                aparam: param
            }
        }
    )
    }
})
```

%{"retval"=> nextId} = Mongo.run_command(MongoPool, %{"eval"=> "return insertHit('127.0.0.1')"})
Mongo.run_command(MongoPool, %{"eval"=> "return updateHitParam(#{nextId}, 8)"})

This does everything I need, but how do you do this using purely the library, (using Mongo.insert_one...)?

Getting the current time in Elixir I worry it would not be properly formatted the way mongodb wants it and itl break datetime queries.

**Comment by ericmj** [comment]
You just show code, can you show actual mongodb documentation that shows this. I have no idea how to implement or show you how to do this if there is no documentation for it.

> Getting the current time in Elixir I worry it would not be properly formatted the way mongodb wants it and itl break datetime queries.

Here is an example of how to encode datetime in a format mongodb expects: https://github.com/michalmuskala/mongodb_ecto/blob/master/lib/mongo_ecto/encoder.ex#L55-L59

**Comment by vans163** [comment]
The example is straight from http://docs.mongodb.org/manual/reference/operator/update/currentDate/

new Date() should be equal to  ... %BSON.DateTime{utc: seconds \* 1000 + div(usec, 1000) ... so thats taken care of. 

Mongo has a scope $currentDate: { lastModified: true } which automatically sets a 'lastModified: new Date()' on the document you are updating.

I think there are too many custom things mongodb can do to implement into a single library.  It seems that if you are not using the mongo shell or calling an internal mongo js function the implementation complexity greatly increases.

**Comment by ericmj** [comment]
> new Date() should be equal to ... %BSON.DateTime{utc: seconds \* 1000 + div(usec, 1000) ... so thats taken care of.

You can do this with this library.

> Mongo has a scope $currentDate: { lastModified: true } which automatically sets a 'lastModified: new Date()' on the document you are updating.

You can do this as well with this library.

But you have not shown documentation for executing custom code outside of `$where`, `mapReduce` or `runCommand eval`. If you want to insert javascript functions you can do `%BSON.JavaScript{code: ...}`.

**Comment by vans163** [comment]
```
You can do this as well with this library.
```

Is there any documentation on how to do that?

```
But you have not shown documentation for executing custom code outside of $where, mapReduce or runCommand eval. If you want to insert javascript functions you can do %BSON.JavaScript{code: ...}
```

Yes I believe its not possible without using run_command.  %BSON.JavaScript writes the function into the document, I am not sure how to have it write the evaluated result of the function (if thats even possible).

**Comment by ericmj** [comment]
> Is there any documentation on how to do that?

I linked code for it and you even repeated the code.

> Yes I believe its not possible without using run_command. %BSON.JavaScript writes the function into the document, I am not sure how to have it write the evaluated result of the function (if thats even possible).

I don't think it's possible, if it is you will have to find a source or documentation for it otherwise it's impossible for me to work on it.
