### ISSUE TITLE
dialyzer problem

### ISSUE THREAD

**Issue by gpad** [elixir-mongo/mongodb#226]
I'm using this library in a project with dialyzer and I'm getting some errors. I create PR #225 to fix it. I hope it will be helpful.

Using dialyzer I discovered some minor bug (check setops in my PR) and some dead code that I removed. Please feel free to comment and tell me if you want that I'll change something.

**Comment by gpad** [comment]
Hi @ankhers Have you have time to check my PR? Do you think that it's possible merge it in master? If there are some thing that requires to be adjusted I'll be glad to take care of them  ...

**Comment by ankhers** [comment]
Merged #225
