### ISSUE TITLE
Unable to compile code, internal error occurred with elixir 1.7.3 on Mac OS X.

### ISSUE THREAD

**Issue by zookzook** [elixir-mongo/mongodb#234]
Using:

    $ mix --version
    Erlang/OTP 21 [erts-10.0.6] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]   [dtrace]

    Mix 1.7.3 (compiled with Erlang/OTP 21)

I got an internal error while compiling:

	mix compile
	==> connection
	Compiling 1 file (.ex)
	Generated connection app
	==> decimal
	...
	==> mongodb
	Compiling 29 files (.ex)
	warning: "not expr1 in expr2" is deprecated. Instead use "expr1 not in expr2" if you require Elixir v1.5+, or "not(expr1 in expr2)" if you have to support earlier Elixir versions
	  lib/mongo/topology.ex:72

	warning: "not expr1 in expr2" is deprecated. Instead use "expr1 not in expr2" if you require Elixir v1.5+, or "not(expr1 in expr2)" if you have to support earlier Elixir versions
	  lib/mongo/topology_description.ex:343

	warning: "not expr1 in expr2" is deprecated. Instead use "expr1 not in expr2" if you require Elixir v1.5+, or "not(expr1 in expr2)" if you have to support earlier Elixir versions
	  lib/mongo/topology_description.ex:397

	Function: recv_buffer/1

	== Compilation error in file lib/mongo/protocol.ex ==
	** (CompileError) lib/mongo/protocol.ex: internal error in beam_record;
	crash reason: {case_clause,{'EXIT',{{badmatch,false},
						  [{beam_utils,defs_list,4,
									   [{file,"beam_utils.erl"},{line,1251}]},
						   {beam_utils,defs,3,
									   [{file,"beam_utils.erl"},{line,1109}]},
						   {beam_utils,defs,3,
									   [{file,"beam_utils.erl"},{line,1158}]},
						   {beam_utils,defs,3,
									   [{file,"beam_utils.erl"},{line,1167}]},
						   {beam_utils,defs,3,
									   [{file,"beam_utils.erl"},{line,1158}]},
						   {beam_utils,defs,3,
									   [{file,"beam_utils.erl"},{line,1184}]},
						   {beam_utils,defs,3,
									   [{file,"beam_utils.erl"},{line,1110}]},
						   {beam_utils,defs,3,
									   [{file,"beam_utils.erl"},{line,1184}]}]}}}

	  in function  compile:'-select_passes/2-anonymous-2-'/3 (compile.erl, line 585)
	  in call from compile:'-internal_comp/5-anonymous-1-'/3 (compile.erl, line 349)
	  in call from compile:fold_comp/4 (compile.erl, line 376)
	  in call from compile:internal_comp/5 (compile.erl, line 360)
	  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 177)
	  in call from compile:'-do_compile/2-anonymous-1-'/1 (compile.erl, line 190)
		(stdlib) lists.erl:1338: :lists.foreach/2
		(stdlib) erl_eval.erl:677: :erl_eval.do_apply/6

Which version should I use? It seems that the code is not compatible with 1.7.3. I running elixir on Mac OS X.

**Comment by zookzook** [comment]
I get it compiled, if I reduce the functions recv_buffer/1 to one:

	  defp recv_buffer(%{socket: {mod, sock}} = s) do
		receive do
		  {^mod, ^sock, _buffer} -> {:ok, s}
		after
		  0 -> {:ok, s}
		end
	  end

**Comment by ankhers** [comment]
I believe this is an issue with OTP 21.0.x. I know at the very least that it was an issue on 21.0.1 based on someone else having the same issue. If you update your Erlang version, it should be resolved.

What you came up with is not the same. In the case of a non ssl connection, the `mod` will be `:gen_tcp`, but you should be receiving on `:tcp`.

**Comment by zookzook** [comment]
You are right. After upgrading erlang to

    iex --version
    Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]     [dtrace]

    IEx 1.7.3 (compiled with Erlang/OTP 21)

it compiles without an internal error. I close this issue.

**Comment by nitinjain1105** [comment]
I am trying to run an elixir app on windows machine. My elixir app uses {:mongodb, ">= 0.0.0"}. I have Elixir 1.7.4 and OTP 21. Do I need to install OTP 21.1?

I am getting the following compilation error:

λ mix deps.compile mongodb
==> mongodb
Compiling 29 files (.ex)
Function: recv_buffer/1
warning: "not expr1 in expr2" is deprecated. Instead use "expr1 not in expr2" if you require Elixir v1.5+, or "not(expr1 in expr2)" if you have to support earlier Elixir versions
  lib/mongo/topology.ex:72


== Compilation error in file lib/mongo/protocol.ex ==
** (CompileError) lib/mongo/protocol.ex: internal error in beam_record;
crash reason: {case_clause,{'EXIT',{{badmatch,false},
                      [{beam_utils,defs_list,4,
                                   [{file,"beam_utils.erl"},{line,1248}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1106}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1155}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1164}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1155}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1181}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1107}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1181}]}]}}}

  in function  compile:'-select_passes/2-anonymous-2-'/3 (compile.erl, line 585)
  in call from compile:'-internal_comp/5-anonymous-1-'/3 (compile.erl, line 349)
  in call from compile:fold_comp/4 (compile.erl, line 376)
  in call from compile:internal_comp/5 (compile.erl, line 360)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 177)
  in call from compile:'-do_compile/2-anonymous-1-'/1 (compile.erl, line 190)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
could not compile dependency :mongodb, "mix compile" failed. You can recompile this dependency with "mix deps.compile mongodb", update it with "mix deps.update mongodb" or clean it with "mix deps.clean mongodb"

**Comment by ankhers** [comment]
Yes, you will need to upgrade your OTP version.
