### ISSUE TITLE
GenEvent.notify/2 is deprecated

### ISSUE THREAD

**Issue by gergo-papp** [elixir-mongo/mongodb#236]
## Deprecation warning
- GenEvent.notify/2 is deprecated, use one of the alternatives described in the documentation for the GenEvent module
- In: lib/mongo/events.ex:5

## Environment:
- Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]
- Elixir 1.6.0 (compiled with OTP 20)

**Comment by ankhers** [comment]
Thanks! Just fixed on master.
