### ISSUE TITLE
Using mongod v3.6.4, test aggregate (Mongo.Test) fails

### ISSUE THREAD

**Issue by zookzook** [elixir-mongo/mongodb#238]
I have started a mongodb with defaults params and the replica set with the `start_mongo.bash` script. Running
```
mix test --exclude ssl
```

I got the error:
```

  1) test aggregate (Mongo.Test)
     test/mongo_test.exs:48
     ** (CaseClauseError) no case clause matching: {:ok, %{cursor_id: 0, docs: [%{"$clusterTime" => %{"clusterTime" => #BSON.Timestamp<1539546016:6>, "signature" => %{"hash" => #BSON.Binary<0000000000000000000000000000000000000000>, "keyId" => 0}}, "code" => 9, "codeName" => "FailedToParse", "errmsg" => "The 'cursor' option is required, except for aggregate with the explain argument", "ok" => 0.0, "operationTime" => #BSON.Timestamp<1539546016:6>}], from: 0, num: 1}}
     code: assert []               = Mongo.aggregate(c.pid, coll, [], use_cursor: false) |> Enum.drop(4)
     stacktrace:
       (mongodb) lib/mongo/cursor.ex:232: anonymous fn/5 in Enumerable.Mongo.SinglyCursor.start_fun/5
       (elixir) lib/stream.ex:1362: anonymous fn/5 in Stream.resource/3
       (elixir) lib/enum.ex:2979: Enum.drop/2
       test/mongo_test.exs:82: (test)
```

I can fix the test by using the `use_cursor: true`

```
    assert []               = Mongo.aggregate(c.pid, coll, [], use_cursor: true) |> Enum.drop(4)
    assert [%{"foo" => 42}] = Mongo.aggregate(c.pid, coll, [], use_cursor: true) |> Enum.take(1)
    assert [%{"foo" => 45}] = Mongo.aggregate(c.pid, coll, [], use_cursor: true) |> Enum.drop(3)
```

I do not know why now, but I think it's the MongoDB version. Can somebody confirm this?

**Comment by ankhers** [comment]
I also get this error when running the tests. I haven't been able to track it down. Admittedly I haven't put too much effort into finding it because the error doesn't show up on travis, nor in my production applications. If you, or anyone else, are able to track it down, I would love to know why it is breaking.

**Comment by zookzook** [comment]
I found a hint (https://docs.mongodb.com/manual/reference/command/aggregate/#dbcmd.aggregate):

>Changed in version 3.6: MongoDB 3.6 removes the use of aggregate command without the cursor option unless the command includes the explain option. Unless you include the explain option, you must specify the cursor option.

In case of the `def aggregate(topology_pid, coll, pipeline, opts \\ []) do` the `cursor` field needs to be specified, even without using a cursor.

I changed the code to:

```
      if cursor? do
        query = query ++ [cursor: filter_nils(%{batchSize: opts[:batch_size]})]
        aggregation_cursor(conn, "$cmd", query, nil, opts)
      else
        if version >= 3 do
          query = query ++ [cursor: %{}]
          aggregation_cursor(conn, "$cmd", query, nil, opts)
        else
          singly_cursor(conn, "$cmd", query, nil, opts)
        end
```

and the unit tests (in case of the MongoDB 3.6.4) now work.

**Comment by ankhers** [comment]
Thanks, I will look into that.
