### ISSUE TITLE
BSON.Objectid.new() arguments example?

### ISSUE THREAD

**Issue by astutecat** [elixir-mongo/mongodb#244]
Hi there - Do you have any advice on which items to pass to this function in order to get a sufficiently random ObjectID?

The secs and counter parameters are pretty obvious for what they should be (judging from https://docs.mongodb.com/manual/reference/method/ObjectId/), but the machine_id and proc_id are less obvious of what their inputs typically should be.

I'm mindful that I don't want to create a situation where I have IDs clashing.

**Comment by ankhers** [comment]
You should probably just be using `Mongo.object_id/0`.

**Comment by astutecat** [comment]
hah, I totally missed that. thanks :)
