### ISSUE TITLE
Compilation error: Mongo.ReadResult.__struct__/0 is undefined, cannot expand struct Mongo.ReadResult

### ISSUE THREAD

**Issue by davidmirallesstarshot** [elixir-mongo/mongodb#246]
I'm very new with this language but I'm a little bit lost and need support on the problems I'm having.

When compiling my solution that's using mongodb library, I'm getting the following error:
```

== Compilation error in file lib/estorage/db/mongodb.ex ==
** (CompileError) lib/estorage/db/mongodb.ex:19: Mongo.ReadResult.__struct__/0 is undefined, cannot expand struct Mongo.ReadResult
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
```

It's happening to me on libraries 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7. It worked in the past with the same library.

The file that gets compilation failed:

```
> defmodule Estorage.Db.MongoDB do
>     alias Mongo.Connection
>     alias Mongo.ReadResult, as: Read
>     alias Mongo.WriteResult, as: Write
> 
>     def find(connection_pid, collection, parameters) do
>         {:ok, %Read{cursor_id: _, docs: data, from: _, num: _}} = Connection.find(connection_pid, collection, parameters, nil)
>         data
>     end
> 
>     def find_one(connection_pid, collection, parameters) do
>         cursor = Connection.find_one(connection_pid, collection, parameters, nil)
>         cursor
>     end
> 
>     def update_one(connection_pid, collection, filter_data, set_data) do
>         Connection.update(
>             connection_pid,
>             collection,
>             filter_data,
>             set_data
>         )
>     end
> ... some more lines
```

Additional information:  
$ cat /usr/lib/erlang/releases/RELEASES
%% coding: utf-8
[{release,"Erlang/OTP","20","9.2",
          [{kernel,"5.4.1","/usr/lib/erlang/lib/kernel-5.4.1"},
           {stdlib,"3.4.3","/usr/lib/erlang/lib/stdlib-3.4.3"},
           {sasl,"3.1.1","/usr/lib/erlang/lib/sasl-3.1.1"}],
          permanent}].

**Comment by ankhers** [comment]
You seem to have written that for a really old version of this library. `Mongo.Connection` and `Mongo.ReadResult` have not been a part of this package since v0.1.1.

**Comment by davidmirallesstarshot** [comment]
yes, I've fixed it by using:
- {:mongodb, git: "https://github.com/ericmj/mongodb.git", tag: "3c481c086607d626b8cf9c8b8e5dc6fe2bc63dfd"},
- {:plug_cowboy, "~> 1.0"},

Anyway, I will need to upgrade the code for the new versions :(

Thanks!
