### ISSUE TITLE
Read preference for secondary nodes has strange incosistent behaviour with different operations

### ISSUE THREAD

**Issue by sashaafm** [elixir-mongo/mongodb#250]
Version: 0.4.7
Elixir: 1.5.2

We're working on a project which we want to read only from secondary nodes of our Mongo cluster. To achieve this we set our options initially as so:
```
options = [
      sort: %{"_id" => 1}, # Sorts in ascending order
      skip: (page - 1) * per_page,
      pool: DBConnection.Poolboy,
      read_preference: Mongo.ReadPreference.defaults(%{mode: :secondary_preferred}),
     slave_ok: true
    ]
```
And we perform two different read operations:

1. Find All: this operation uses a given field to return all the objects with that field and how many there are. First, it uses `Mongo.count!/4` to get how many objects exist with that field, followed by a `Mongo.find/4`, which retrieves all those objects fitting into a given page size.
2. Find By ID: this operation return an object with a given field (like the previous op) and a given ID. It only relies on `Mongo.find/4` to fetch that object.

With the above configuration both operations work, but we weren't able to determine if the driver is in fact reading from the secondary nodes.

However, a strange behaviour arises when setting `slave_ok: false`. With this option set as `false`, the second operation works, but the first fails with 
```
 message: "command failed: not master"}, stack: [{Mongo, :count!, 4, [file: 'lib/mongo.ex', line: 311]}
```

This feels very strange to us. As specified here in the Mongo [Read Preference docs](https://docs.mongodb.com/manual/core/read-preference/#read-preference-modes) we're supposed to get this behaviour:

> In most situations, operations read from secondary members but if no secondary members are available, operations read from the primary.

Since we've got both primary and secondary nodes up in our cluster, we should be reading from secondary nodes.

Continuing on and reading about [slaveOk](https://docs.mongodb.com/manual/reference/method/rs.slaveOk/index.html#rs-slaveok) we understand that this allows the connection to read from secondary nodes.

So, let's summarise this:

1. Read Preference to secondary tells the driver to read from the secondary nodes whenever possible.
2. `slaveOk` set to `true` actually allows the driver to read from the secondary nodes.

Then we've got these two configurations as explained above:

| Configuration |   Read Preference   | SlaveOk |                           Result                           |
|:----------:|:-------------------:|:-------:|:----------------------------------------------------------:|
|      1     | secondary_preferred |   true  | Both operations work, but unsure if reading from secondary |
|      2     | secondary_preferred |  false  | Find by ID works, but Find All fails when performing count |

The fact that count fails to perform the operation because it's trying to read from the secondary ("not master") without `slaveOk` rises the following questions:

1. Why the `Mongo.find` function is working? Is it because the `count` function is reading from the secondary and failing while the `find` function is seemingly reading from the primary and working? If yes, is this expected?
2. How can we be sure that setting `slaveOk` to `true` is actually making both `count` and `find` read from the secondaries and not in fact just allowing `count` to read from the secondary while `find` is still reading from the primary as hinted in Configuration 2?

Our fear here is that a bug may be underlying somewhere in these operations because the behaviour is inconsistent across the API. It's not clear if setting the proper configuration is giving us the intended behaviour or simply bypassing the problems explained above.

Thank you for your time!

**Comment by tjsousa** [comment]
This should be solved by #261
