### ISSUE TITLE
Running tests using designated test DB

### ISSUE THREAD

**Issue by MarkPare** [elixir-mongo/mongodb#260]
Thanks for the great library.

I'm trying to run tests on my context functions but I don't see a documented way of specifying use of a designated test DB. As a result, whenever I run my tests, the data is inserted into my dev DB.

Did I miss something in docs or is there an easy workaround?

Thanks for any suggestions!

**Comment by ankhers** [comment]
Usually you would have a `config/dev.exs` and a `config/test.exs` file to separate your test, development, whatever configurations.

Put

```
import_config "#{Mix.env}.exs"
```

in your `config/config.exs`, and then you can specify configuration files for any environment you choose.

**Comment by MarkPare** [comment]
Thanks for your response.

I think I was confused by this part of the docs:

```
If you're using pooling it is recommend to add it to your application supervisor:

def start(_type, _args) do
  import Supervisor.Spec

  children = [
    worker(Mongo, [[name: :mongo, database: "test", pool: DBConnection.Poolboy]])
  ]

  opts = [strategy: :one_for_one, name: MyApp.Supervisor]
  Supervisor.start_link(children, opts)
end
```

where the database name is passed directly as a string to the worker initiation.

What do you think about something like:
```
children = [
      worker(Mongo, [[name: :mongo, database: Application.fetch_env(:my_app, :db,  :name), pool: DBConnection.Poolboy]])
    ]
```

Would this be a reasonable strategy for achieving above-stated functionality? Or would you recommend something else?

**Comment by ankhers** [comment]
Yes, that will be fine.

**Comment by MarkPare** [comment]
This is my setup which is working.  Thanks for the help.

```
# dev.exs

config :my_app, :db, name: "my_app_dev"

# prod.exs

config :my_app, :db, name: "my_app_prod"

# test.exs

config :my_app, :db, name: "my_app_test"

# application.ex
...
children = [
      worker(Mongo, [[name: :mongo, database: Application.get_env(:my_app, :db)[:name], pool: DBConnection.Poolboy]])
]
```
