### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by 728443778** [elixir-mongo/mongodb#263]
hi,when  i use ecto_sql and mongodb,i found ecto_sql (versions 3.0.0 to 3.0.3) requires ~> db_connection 2.0, mongodb (versions 0.4.0 and 0.4.1) requires ~> db_connection 1.0,i want to use ecto_sql 2.0,but not found it on hex.pm,so i only use {:db_connection, "~> 2.0", override: true},but mongodb driver not work,so Excuse me. Upgrade, I tried, found not enough ability

**Comment by ankhers** [comment]
Thanks for the report. I'm going to close this because we already have a ticket for upgrading the db_connection package (#235), and we have a PR (#248) to deal with it. It just need to be tested to ensure the upgrade is proper.
