### ISSUE TITLE
tcp_connect() - mention hostname & port in error message

### ISSUE THREAD

**Issue by sunaku** [elixir-mongo/mongodb#264]
Hello,

When you connect to multiple hosts in a replica set and one or more of those hosts are down, connection error messages in `tcp_connect()` are currently ambiguous because they don't mention which hostname/port the error message is actually referring to:

```
15:16:53.287 [error] Mongo.Protocol (#PID<0.255.0>) failed to connect: ** (Mongo.Error) tcp connect: connection refused - :econnrefused
```

Please add hostname/port information to the error message so that users can know exactly which host(s) in the replica set are actually experiencing connectivity issues.  For your reference, here is the location in the codebase where this can be impemented: https://github.com/ankhers/mongodb/blob/01bd4eaa01052f7faa3f6984c6c71db4b3cd7c7c/lib/mongo/protocol.ex#L122

Thanks for your consideration.

**Comment by ankhers** [comment]
Thanks! Fixed in d2ffecd.
