### ISSUE TITLE
How to configure TTL for records stored in Mongo

### ISSUE THREAD

**Issue by nitinjain1105** [elixir-mongo/mongodb#269]
Hi @ankhers ,

I need to remove records from Mongo after specific time, how can I set TTL?

My record looks like:

{
    "_id" : ObjectId("5c508a54b6befa1338b049d9"),
    "message" : "Test Message",
    "node" : "beam@localhost.com",
    "timestamp" : ISODate("2019-01-29T12:16:04.863Z")
}

Please Help

Thanks
Nitin

**Comment by ankhers** [comment]
Right now you will need to use a command to do that.

```
create_index = [
  createIndexes: "collection",
  indexes: [
    ...
  ]
]

Mongo.command(:mongo, create_index)
```

All options can be found [here](https://docs.mongodb.com/manual/reference/command/createIndexes/#dbcmd.createIndexes). 

It is probably worth putting in a function to create indexes that is a wrapper for this command.
