### ISSUE TITLE
Mongo.command/3 optimized for reads, not writes

### ISSUE THREAD

**Issue by sunaku** [elixir-mongo/mongodb#272]
Hello,

I'm using `Mongo.command/3` to perform [batched updates](https://docs.mongodb.com/manual/reference/command/update) of the following form on a multi-node replicaset:

```elixir
[
  update: "mycollection",
  updates: [
    [
      q: %{_id: %{"$gte": 39, "$lt": 169}},
      u: %{"$set": %{path: [0], tier: 1}},
      multi: true
    ],
    # 99_999 more items (totaling ~16MB) go here
  ],
  ordered: false
]
```

However, the `Mongo.command/3` function is [currently _always_ optimized for reads](https://github.com/ankhers/mongodb/blob/v0.4.7/lib/mongo.ex#L516) since it always calls `Mongo.select_server/3` with the `:read` intention and therefore ends up connecting me to a _random node_ in the replicaset instead of always connecting directly to the Primary (which is the only node in the replicaset that can handle writes).  As a result, I often encounter connection errors (as enumerated below) on heavier workloads where I'm sending lots of batched updates to MongoDB because, by chance, they're randomly getting routed to non-Primary nodes in the replicaset who are then rejecting my batched update commands.

```elixir
%DBConnection.ConnectionError{message: "connection not available because of disconnection"}
%Mongo.Error{code: nil, message: "tcp recv: unknown POSIX error - :timeout"}
```

Would it be possible to tell `Mongo.command/3` about my intention to perform a write (instead of a read) so that it calls `Mongo.select_server/3` with the `:write` intention, just like `Mongo.update_one/5` gets to do?

Thanks for your consideration.

**Comment by ankhers** [comment]
The `:read` intention just means that the command _can_ read. It is not 100% write like `Mongo.insert_one/4`. The first line in that function is setting up a default `:read_preference` that will read from the primary.

If you were attempting a write command on a secondary, the return value of the command function would be 

``` elixir
{:error, %Mongo.Error{code: 10107, host: nil, message: "command failed: not master"}}
```

It looks like driver is disconnecting from your server(s) for some reason. You would have to dig into your server and machine logs to figure out why the disconnect happened.

**Comment by sunaku** [comment]
Thanks, I followed your advice and switched to using a *shared connection pool*, which has solved the issue. :+1:
