### ISSUE TITLE
Cannot make a call to `Mongo.show_collections`

### ISSUE THREAD

**Issue by foggy1** [elixir-mongo/mongodb#276]
I'm running `:mongodb, "0.4.7"`.

Elixir version info:

Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.4 (compiled with Erlang/OTP 21)

### Current behavior

If I try to call `Mongo.show_collections(:mongo)` or `Mongo.show_collections(:mongo, pool: my pool setup)` I get the following error (of either arity)

```
 (UndefinedFunctionError) function Mongo.show_collections/2 is undefined or private
```

### Expected behavior

I see `show_collections/2` (and `show_collections/1`) in the codebase (and I see that they aren't private), but I don't seem to be able to invoke them. Am I mistaken and/or is there another way for me to list the collections in my db?

Thanks!

**Comment by ankhers** [comment]
That function was only recently introduced and has not been released yet. I will make a release shortly.
