### ISSUE TITLE
%Protocol.UndefinedError{description: "", protocol: Enumerable, value: :error}

### ISSUE THREAD

**Issue by nitinjain1105** [elixir-mongo/mongodb#278]
Hi @ankhers 

I am using Mongo.find/4 to fetch data from Mongo DB. I get this error:

`%Protocol.UndefinedError{description: "", protocol: Enumerable, value: :error}`

Structure of Document Stored in Mongo is -

```
{
    "_id" : ObjectId("5c66635966c541e09749a209"),
    "node" : "my_node_name",
    "timestamp" : ISODate("2019-04-30T15:56:19.000Z")
}

```
I am using {:mongodb, "== 0.4.7"}

Please help.

Thanks
Nitin

**Comment by ankhers** [comment]
Would you be able to share the code that you used to find this issue?

**Comment by nitinjain1105** [comment]
```
Mongo.find(mongo_name, "coll", %{"$query": query_map}, pool: DBConnection.Poolboy)
|> Enum.to_list()
|> Enum.map(fn x ->
  Map.update!(x, "_id", fn x -> Base.encode16(x.value, case: :lower) end)
end)
|> Enum.to_list()
|> Enum.map(fn x -> Map.take(x, String.split(select <> "," <> "_id", ",")) end)
```


P.S. - Value of:
select - "node,timestamp,_id"
query_map - %{"node" => "nodename@hostname"}

**Comment by ankhers** [comment]
Can you give the full error message you are getting?

**Comment by nitinjain1105** [comment]
This is the only error message -
`%Protocol.UndefinedError{description: "", protocol: Enumerable, value: :error}`

**Comment by ankhers** [comment]
There is no stacktrace or anything?

My best guess is that the `Mongo.find/4` call is returning `:error` instead of a cursor and `Enum.to_list(:error)` would be doing something similar to what is happening. You should check the values returned at each stage of that pipe.

And for what it's worth, both of the `Enum.to_list/1` calls are unnecessary.

**Comment by nitinjain1105** [comment]
Let me try taking the output at each stage of the pipe
