### ISSUE TITLE
Too many connections created

### ISSUE THREAD

**Issue by rblack** [elixir-mongo/mongodb#284]
Hi!
Using mongodb v0.5.0 with single MongoDB 3.4 instance. Setting`pool_size` option to 20 leads to 420 connections created according to `db.serverStatus().connections` in a mongodb shell. Tried to determine whether there is some pattern and found out the following (first value pool_size, second — current connections including one made from shell):
2: 7
4: 21
6: 43
10: 111
15: 241
20: 421
Tested in iex shell with `Mongo.start_link(url: “mongodb://localhost:27017/db-name”, pool_size: 20)`
Docs are outdated at the moment, so I may be missing something, but anyway this is odd behavior.

**Comment by ankhers** [comment]
Thank you for catching and reporting this! It is an issue with our internal monitors. Each monitor should only have a single connection, but we are accidentally starting a pool of connections. Resolved in 8979c0abd30f984ecadd2b1e23d2649a9cf8ecfa.
