### ISSUE TITLE
Actual mapping of BSON objects to Elixir terms is not consistent with documentation

### ISSUE THREAD

**Issue by gianluca-nitti** [elixir-mongo/mongodb#288]
On [this page](https://hexdocs.pm/mongodb/0.4.7/readme.html#data-representation), I'm reading `This driver chose to accept both maps and lists of key-value pairs when encoding but will only decode documents to lists.`.

Howerver, I noticed that in my project using 0.4.7 (as the linked page of the docs) the following happens:
```
iex(27)> Mongo.insert_one(:conn_pid, "my_collection", %{"an_object" => %{"field1" => "foo", "field2" => "bar"}})  
{:ok,
 %Mongo.InsertOneResult{inserted_id: #BSON.ObjectId<5cdd2c6b421aa948e848f603>}}

iex(28)> Mongo.find(:conn_pid, "my_collection", %{}) |> Enum.to_list()                                          
[
  %{
    "_id" => #BSON.ObjectId<5cdd2c6b421aa948e848f603>,
    "an_object" => %{"field1" => "foo", "field2" => "bar"}
  }
]
```
As you can see, both the root document retrieved from the collection (with `_id` and `an_object` keys) and the inner object (with `field1` and `field2` keys) are actually being decoded as maps instead of lists of key-value pairs.

**Comment by ankhers** [comment]
Thanks for pointing this out! There must have been a change somewhere along the way and the documentation was never changed. Would you like to submit a PR for a documentation fix?

**Comment by gianluca-nitti** [comment]
Sorry for the delay, PR opened
