### ISSUE TITLE
Add Mongo.find_one function

### ISSUE THREAD

**Issue by ericmj** [elixir-mongo/mongodb#29]

**Comment by fairbairn** [comment]
This is a biggie.  We're currently having to perform a specification around find and then attempt to pull and validate a single record returned.  Clearly not as efficient as a direct find_one.

```
  def find_one_record(filter, opts) do
    try do
      cursor = Mongo.find(get_pool(opts), opts[:collection], filter, clean_opts(opts))
      records = Enum.to_list(cursor)
      record = records |> List.first
      cond do
        is_nil(record)            -> {:error, :notfound}
        Enum.count(records) == 1  -> {:ok, record} |> handle_result(opts)
        true                      -> {:error, :incorrect}
      end
    rescue
      e in Mongo.Error -> handle_exception(e, opts)
    end
  end
```

**Comment by michalmuskala** [comment]
You can pass a `limit: 1` option to find, to make sure you get at most one result. That's what I do in the ecto adapter currently.

**Comment by fairbairn** [comment]
That will speed up our routine in the interim, thanks, but we should support it natively if we can.

**Comment by elie222** [comment]
Was this never added? Using `limit: 1` each time is a bit of a pain.

**Comment by ericmj** [comment]
@elie222 A PR would be appreciated.

**Comment by ankhers** [comment]
@ericmj I believe this can now be closed.
