### ISSUE TITLE
TTL Indexes in migration

### ISSUE THREAD

**Issue by Orange-Men** [elixir-mongo/mongodb#299]
Hi
Is there any way to add TTL indexes in migration?

Thanks

**Comment by ankhers** [comment]
There is currently no helper function to do this. You will need to use `Mongo.command/3`. Something like 

```
command = [
  createIndexes: "collection",
  indexes: [
    key: %{
      field_1: 1,
      field_2: -1
    },
    name: "some_index_name",
    expireAfterSeconds: 86400
  ]
]

Mongo.command(pid, command)
```

You can find more details [here](https://docs.mongodb.com/manual/reference/command/createIndexes/#definition)
