### ISSUE TITLE
Stream.resource from cursor/Mongo.find

### ISSUE THREAD

**Issue by amokan** [elixir-mongo/mongodb#30]
I'm sure this is due to my inexperience, but I'm trying to find an example of setting up a stream from a cursor.

I can see a number flaws in my approach and figure there is likely a better way to do this.

```
def doc_stream(some_criteria) do
  Stream.resource(
    fn -> iteration end,
    fn(iteration) ->
      IO.puts "iteration: #{iteration}"
      data = Mongo.find(SomePool, "collection_name", %{"field" => some_criteria, limit: 1, skip: iteration)
      if Enum.empty?(data) do
        {:halt, iteration}
      else
        {[Enum.at(data, 0)], iteration + 1}
      end
    end,
    fn(iteration) -> iteration end
  )
end
```

```
doc_stream |> Enum.take(10)
```

My goal is to not put a ton of pressure on the mongo servers when trying to work through massive collections in batches. I'd like to utilize streams and async processes to work on small chunks and only pull the next n-number of documents when its time to use them.

My issue with what I have is that if I take 10, its going to fire 10 queries at the database I assume. That is probably not ideal.

But before I sink more time into this and reinvent the wheel, I figured one of you may have a better approach or maybe this is silly altogether?

**Comment by michalmuskala** [comment]
I believe the cursors already implement the `Enumerable` protocol and can be used with both `Enum` and `Stream` module to lazily load the data as it's needed - there's no need for additional wrapping. You can control the size of a batch with the `batch_size` option.

**Comment by amokan** [comment]
looks like that works... I haven't watched the backend, but I have a suspicion I can play with the batch size like you mentioned and get the results I'm after

```
Mongo.find(SomePool, "collection_name", %{"field" => some_criteria})
|> Stream.map(fn x -> Foo(x) end)
```

Thanks @michalmuskala !
