### ISSUE TITLE
Regex Exp

### ISSUE THREAD

**Issue by jsayegh** [elixir-mongo/mongodb#306]
What's the equivalent in of this filter in elixir 

```
    {$or:[
        {"project_information.title":{"$regex": /2/i }},
        {"project_information.collection_target":{"$regex": /2/i }}
    ]}
```
The following doesn't work : 
```
r = %BSON.Regex{pattern: "/2/i", options: ""}

"$or" => [
    #     %{"project_information.title" => %{"$regex" => r}},
    #     %{"project_information.collection_target" => %{"$regex" => r}}
    #   ]
```
It appears that only a string that starts expression is supported
For example this works 
```
%BSON.Regex{pattern: "Project*", options: ""}
```

But this doesn't 

For example this works 
```
%BSON.Regex{pattern: "*oject*", options: ""}
```

**Comment by jsayegh** [comment]
Never mind after reading this : https://docs.mongodb.com/manual/reference/operator/query/regex/

The equivalent is: 

```
r = %BSON.Regex{pattern: "2", options: "i"}
```

**Comment by ankhers** [comment]
> ```
> r = %BSON.Regex{pattern: "/2/i", options: ""}
> ```

You will want to use

```
r = %BSON.Regex{pattern: "2", options: "i"}
```

> It appears that only a string that starts expression is supported
> For example this works 
> ```
> %BSON.Regex{pattern: "Project*", options: ""}
> ```
> 
> But this doesn't 
> 
> For example this works 
> ```
> %BSON.Regex{pattern: "*oject*", options: ""}
> ```

This is the exact same in mongo's own shell. If you try 

```
db.collection.find({"project_information.title": {"$regex": '*roject*',
"$options": 'i'}})
```

You will receive an empty result. Whereas if you used the 'Project*'
version, you would get results.

What exactly are you trying to accomplish with the leading asterisk? In
a regex, an asterisk is used to mean "zero or more of the thing coming
before it". In your case, there is nothing in front of the asterisk, so
there is nothing for it to do. I suspect you may be looking for the dot,
which will match any single character. Maybe you want to use

```
r = %BSON.Regex{pattern: ".roject", options: "i"}
```

This will return all results that have at least one character before the
substring "roject".
