### ISSUE TITLE
Add collection drop and handle case exceptions

### ISSUE THREAD

**Issue by fairbairn** [elixir-mongo/mongodb#31]
Add a .drop() function to drop a collection.

We performed it manually using a run_command but if the collection does not exist, an uncaught exception occurs...

*\* (CaseClauseError) no case clause matching: %{"errmsg" => "ns not found", "ok" => 0.0}

As a guidepost, within our wrapper lib, we're handling like this presently..

  def drop_collection(collection) do
    try do
      %{"ok" => 1.0} = Mongo.run_command(@pool, %{:drop => collection})
      :ok
    rescue
      e in CaseClauseError ->
        Logger.debug "#{inspect e}"
        :error
    end
  end

**Comment by ericmj** [comment]
I don't think a drop function should be added because we cant add functions for every possible command. But the case should be fixed and a I will add functions that return error tuples instead of raising.

**Comment by fairbairn** [comment]
We're currently doing this which works fine for us...

```
  def drop(collection, opts \\ []) do
    drop_collection(collection, get_options(opts))
  end
```

```
  def drop_collection(collection, opts) do
    try do
      %{"ok" => 1.0} = Mongo.run_command(get_pool(opts), %{:drop => collection})
      :ok
    rescue
      e in CaseClauseError ->
        Logger.debug "#{inspect e}"
        :error
    end
  end
```

Ignore our other functions (ie, get_pool and get_options), these simply allow us to define specificity at our wrapper layer so we don't have to pass pool into the calls every time.

We can thus do things like..

Customers.find_many

**Comment by edgurgel** [comment]
I can send a PR changing `run_command` to return `{:ok, document} | {:error, tuple}` and add `run_command!` as well. What happens with other functions using `run_command`? Will they need to have their bang versions as well (`distinct!`, `count!`, etc)?

**Comment by ericmj** [comment]
@edgurgel We should have bang and non-bang variants of all functions that can fail in the `Mongo` module. Feel free to start working on this :)

**Comment by edgurgel** [comment]
I don't know how I missed this comment but I will work on this soon! Sorry for the super delay.
