### ISSUE TITLE
How to use the Mongo.command function

### ISSUE THREAD

**Issue by otboss** [elixir-mongo/mongodb#312]
In the documentation for this database driver little is said about how exactly to use the Mongo.command function.

Reference: https://hexdocs.pm/mongodb/Mongo.html#command/3

I searched online for examples on how to use it but with no luck.
After some experimentation, If I wanted to do a find query then i would have: 

```
          Mongo.command(:db_connection, %{
            find: "addresses",
            projection: %{}
          })

```
I wanted to use the Mongo.command function specifically to create a new user. How does the Mongo.command function work? Is there any way I can run the standard Mongo db function syntax?

**Comment by ankhers** [comment]
create_user_command = %{
  createUser: "username",
  pwd: "some_password",
  roles: []
}

Mongo.command(pid, create_user_command)

To view all available parameters for this command, please read the
following page https://docs.mongodb.com/manual/reference/command/createUser/#dbcmd.createUser

**Comment by otboss** [comment]
I was hoping that there was some way of executing Mongo queries just as they are in the docs (javascript) but there doesn't seem to be a way. Thanks though
