### ISSUE TITLE
Suggestion: Provide a collection wrapper to allow cleaner access

### ISSUE THREAD

**Issue by aselder** [elixir-mongo/mongodb#315]
I'm writing an application to connect to a legacy MongoDB database and I'm finding myself writing similar code over and over.

My goal is not to have to remember the collection name every where I want to call queries from, so I end up with a lot of modules that are just wrapping the `Mongo` function with the topology_pid and collection hard code.

I eventually abstracted this to a module like the following:

```
defmodule Mongo.Collection do
  @moduledoc false

  defmacro __using__(collection_name, mongo_pid \\ :mongo) do
    quote do
      @collection_name unquote(collection_name)

      def find_one(filter, opts \\ []) do
        Mongo.find_one(unquote(mongo_pid), @collection_name, filter, opts)
      end

      def insert_one!(doc, opts \\ []) do
        Mongo.insert_one!(unquote(mongo_pid), @collection_name, doc, opts)
      end
    end
  end
end
```

This allows me to write something like:

```
defmodule ApiV1.Items.Item do
  use Mongo.Collection, "items"
end

ApiV1.Items.Item.find_one(%{_id: BSON.ObjectId.decode!(id)})
```

Alternatively, we could do something like Ecto where we had a `Mongo.Repo` module that would encapsulate the topology_pid, and the collection module would just have the collection name. For example:

```
defmodule MongoRepo do
  use Mongo.Repo, name: :mongo (or opt_app: :my_app)
end

defmodule ApiV1.Items.Item do
  use Mongo.Collection, "items"
end

MongoRepo.find_one(ApiV1.Items.Item, %{_id: BSON.ObjectId.decode!(id)})
```

I'd love to hear people thoughts. I'm happy to put together a PR if people think either of this approaches is valuable.

**Comment by kblake** [comment]
Could you pull up `@mongo_pid unquote(mongo_pid)` too?

The first solution looks ActiveRecord-y and the second one looks Ecto-y. Maybe for consistency go the the 2nd option?

**Comment by kblake** [comment]
Optional: Embedded schemas may get some mapping and validations before inserting into Mongo.

**Comment by Ch4s3** [comment]
I think I would much prefer the second approach, as the first one feels a bit too magical.

@kblake's idea to combine the second approach with embedded schemas for validation sounds like a real win.

**Comment by ankhers** [comment]
I really like this idea. However, it is out of scope for this package. This is just meant to be a basic driver that can be used in order to talk to a mongo database.

If anyone is interested, maybe we could get [mongodb_ecto](https://github.com/mongodb_ecto) back up and running. Or, I recently heard about [bongo](https://github.com/bombinatetech/bongo). I have not used it myself though, so I am not sure how it works or what it's goals are.

**Comment by aselder** [comment]
@ankhers I'd love to set mongodb_ecto back up and running. I'll take a look at what it would need to work with Ecto 3. I'll also continue developing what I'm working on as part of our app and see what might be extractable from there.

**Comment by ankhers** [comment]
That would be great! Feel free to get a hold of me by email (should be listed on my profile), IRC or slack if you have any questions about anything.
