### ISSUE TITLE
Using explain to analyse the query before executing.

### ISSUE THREAD

**Issue by vik228** [elixir-mongo/mongodb#323]
Hey, 
How can i use explain to analyse my queries before executing?

**Comment by ankhers** [comment]
This driver does not currently have a dedicated function for this. However, you can use the [`explain` command](https://docs.mongodb.com/manual/reference/command/explain/).

```elixir
Mongo.command(pid, %{ 
  explain: %{ 
    count: "products", 
    query: %{ quantity: %{ "$gt": 50 } } },
  verbosity: "queryPlanner"
  }
)
```

If you would like to contribute a dedicated function for this, I would gladly merge it.

**Comment by ankhers** [comment]
I am going to close this. If you have any other questions related to this, please feel free to re-open.
