### ISSUE TITLE
How to do deep queries with multiple level cursors

### ISSUE THREAD

**Issue by paulrusu8** [elixir-mongo/mongodb#327]
I have posted this question on stackoverflow.com, but I think it might get more specialized attention here so I repost it:

I am using the mongodb driver from https://github.com/ankhers/mongodb to query a mongodb database in an elixir/phoenix project. In another question, I asked about how to query nested jsons. Another issue would be how to query inserted documents. For example, I can do the following in python 
  

    date_=db['posts']['name'][name]['date'][date]

Here, 'posts' is the name of the collection, and the others are inserted documents. For example, one 'date' document was inserted through:

      db['posts']['name'][name].insert_one({"date":date})

When I want to obtain all the inserted dates in python, I can do

    date_list=[]
    def get_date(db):
      db_posts_name=db['posts']['name'][name]
      for date_query in db_posts_name.find():
            date_list.append(date_query["date"])  

 

But I am at a loss in elixir/phoenix to do the same thing because if I do something like

          list =
            :mongo
            |> Mongo.find("posts", %{})
            |> Enum.fetch(4)
            |> elem(1) 
            |> Map.fetch("name")
            |> elem(1)
          new_list =
            :mongo
            |> Mongo.find("posts", %{"name" => list})
          another_list=new_list.find("date",%{})

I get error 

    Called with 3 arguments

    %Mongo.Cursor{coll: "posts", conn: #PID<0.434.0>, opts: [slave_ok: true], query: %{"name" => name}, select: nil}
    :find
    []

Is there a way to do this ?

**Comment by ankhers** [comment]
I'm sorry, I don't entirely follow. Would you be able to just show an example collection (just a list of maps), and tell me exactly what data you want to get from it, and I should be able to come up with a query for you,

**Comment by paulrusu8** [comment]
Do you mean the output of the python code above ?

**Comment by paulrusu8** [comment]
The question is really if there is a possibility to use the find-function at multiple levels as there is in python (see, again, code above).

**Comment by ankhers** [comment]
There is not. After the initial find operation, this driver will query your database and return a cursor with which you will get your results. The cursor, however, is an `Enumerable`. This would allow you to "find" the items you want within the returned documents by using any of the functions within the `Enum` module. I would generally advise against that though and that you should just query the database for the actual information you are wanting.

Just out of curiosity, what is the name of the python package that you are using?

**Comment by paulrusu8** [comment]
Thank you. I guess my mongodb collection structure was not good to begin with. To your question, I am using the python package pymongo (which seems to be the go-to mongodb driver in python).

**Comment by ankhers** [comment]
I am going to close this. If you have anything else for this issue, please feel free to re-open the issue.
