### ISSUE TITLE
Add ability to specify database on the use Mongo.Pool options

### ISSUE THREAD

**Issue by fairbairn** [elixir-mongo/mongodb#34]
Would like the ability to also define the database when defining the pool definition itself, instead of specifying the database on start_link.  Since the pool is directly tied to the database, this keeps it cleaner.

The existing approach is:

defmodule DatabasePool do
  use Mongo.Pool, name: **MODULE**, adapter: Mongo.Pool.Poolboy
end

but then elsewhere having to perform a DatabasePool.start_link(database: "my_database").

Would also like the ability to do this instead...

defmodule DatabasePool do
  use Mongo.Pool, name: **MODULE**, adapter: Mongo.Pool.Poolboy, database: "my_database"
end

DatabasePool.start_link

**Comment by michalmuskala** [comment]
You can always define a 0-artiy additional `start_link` function on your pool that would merge default arguments:

``` elixir
def start_link do
  start_link(database: "default_database")
end
```

**Comment by fairbairn** [comment]
We want to specify the database in the Mongo.Pool use statement.  It doesn't allow that today.

The current start_link has database as a required field as well.  We want it to not be required if we've defined in the use statement.
