### ISSUE TITLE
How to disable server-side javascript operation as configuration

### ISSUE THREAD

**Issue by iteron-yasir** [elixir-mongo/mongodb#340]
I've checked some online material. There are two solutions, one is editing mongod.conf () file another one is **mongod --no-scripting**. I think the first one is a permanent one. How can I achieve that?. I can't able to find that mongod.conf file

**Comment by hauleth** [comment]
I do not understand what you are asking for. This is Elixir's MongoDB client library so it has nothing to do with `mongod.conf` at all.

**Comment by iteron-yasir** [comment]
Sorry for the wrong question. I was using alphine-mongo container and I can't able to find **mongod.conf** in that container. So, I thought by using Mongo.start_link() options. we can set those configurations. Is there is any way to set that configuration in the container?
