### ISSUE TITLE
Replica sets support

### ISSUE THREAD

**Issue by vitalis** [elixir-mongo/mongodb#35]
@ericmj  I think that adding replica set support will really boost the elixir / phoenix community.
Using mongodb in production without replica set it's not really possible. My company has a project that I really would like to migrate to phoenix and it's impossible without replica set support. I think there is a lot of developers in the same position. If you need help I can try and add the replica set support myself. If you already working on it I would like to help anyway I can.

**Comment by ericmj** [comment]
Replica sets is the next thing I will be working on, but I've been busy with Elixir core and Hex lately so I haven't had time to work on it. If you can help out that would be appreciated.

There are workarounds to get some form of replica support. You can put a `mongos` instance in front of your servers that will handle the replica set. You can also implement the failover yourself if you disconnect from the main server, remember to check with `ismaster` to verify you didn't connect to the replica. This is what we do in production where I work.

**Comment by rradz** [comment]
There is a fork https://github.com/datanoise/mongodb that implements switching. Would you consider merging the changes so that feature is supported? I don't have knowledge and time to properly test the solution, but it seems simple enought and working.

**Comment by ericmj** [comment]
@rafal-radziszewski If you can package it into a PR and add tests for it I would be happy to merge it.

**Comment by Wijnand** [comment]
Any update on this? Or is it better to use this fork for now?

**Comment by boriscy** [comment]
I would like to know if there is replication or it's on the road for mongodb driver, also have a project that wants to use mongodb with phoenix but really needs replication

**Comment by ericmj** [comment]
There is no replication support and I don't have time to work on it personally. There is an ongoing PR [1] for full support according to the driver specifications but there hasn't been much activity on that PR recently and I don't know if it's ready for review yet. You should check in on that PR if you want to know the status.

[1] https://github.com/ericmj/mongodb/pull/69

**Comment by johnnyshields** [comment]
FYI current work on Replica sets is now in PR #93

**Comment by ankhers** [comment]
And again in #124

**Comment by ankhers** [comment]
#124 has just been merged. I will be closing this ticket. I will make a release for it shortly.
