### ISSUE TITLE
System.stacktrace/0 is deprecated, use __STACKTRACE__ instead

### ISSUE THREAD

**Issue by gergo-papp** [elixir-mongo/mongodb#352]
https://github.com/kobil-systems/mongodb/blob/bccfe80a59c2499077c16b9ecaa5eabb6161b919/lib/mongo/session.ex#L93

**Comment by IgorPolyakov** [comment]
@joeapearson 

fixed in https://github.com/elixir-mongo/mongodb/pull/364

https://github.com/elixir-mongo/mongodb/blob/master/lib/mongo/session.ex 93 line

**Comment by joeapearson** [comment]
Thanks @gergo-papp for the original report.  Thanks @IgorPolyakov for checking on it.
