### ISSUE TITLE
insert_one failing

### ISSUE THREAD

**Issue by refriedchicken** [elixir-mongo/mongodb#36]
When I follow the instructions on the Readme I get an error doing an insert:

iex(4)> Mongo.insert_one(MongoPool, "crawl_report", %{"field" => 10})
*\* (ArgumentError) argument error
    (stdlib) :ets.lookup_element(Mongo.IdServer, :machineprocid, 2)
             lib/mongo/id_server.ex:52: Mongo.IdServer.new/0
             lib/mongo/connection.ex:134: Mongo.Connection.add_id/1
             lib/mongo/connection.ex:102: Mongo.Connection.assign_ids/1
             lib/mongo/connection.ex:79: Mongo.Connection.insert/4
    (stdlib) timer.erl:181: :timer.tc/2
             lib/mongo/pool/poolboy.ex:36: Mongo.Pool.Poolboy.run/2
             lib/mongo/pool.ex:142: Mongo.Pool.run_with_log/5

However if I manually run Mongo.IdServer.start_link the insert works:

iex(3)> Mongo.insert_one(MongoPool, "crawl_report", %{"field" => 10})
*\* (ArgumentError) argument error
    (stdlib) :ets.lookup_element(Mongo.IdServer, :machineprocid, 2)
             lib/mongo/id_server.ex:52: Mongo.IdServer.new/0
             lib/mongo/connection.ex:134: Mongo.Connection.add_id/1
             lib/mongo/connection.ex:102: Mongo.Connection.assign_ids/1
             lib/mongo/connection.ex:79: Mongo.Connection.insert/4
    (stdlib) timer.erl:181: :timer.tc/2
             lib/mongo/pool/poolboy.ex:36: Mongo.Pool.Poolboy.run/2
             lib/mongo/pool.ex:142: Mongo.Pool.run_with_log/5
iex(3)> Mongo.IdServer.start_link
{:ok, #PID<0.203.0>}
iex(4)> Mongo.insert_one(MongoPool, "crawl_report", %{"field" => 10})
{:ok,
 %Mongo.InsertOneResult{inserted_id: #BSON.ObjectId<1dfbc07783152906278464a1>}}

Is this expected behavior or is something wrong?

**Comment by ericmj** [comment]
What instructions in the readme? :)

Like all your dependencies that you will use in production you should add it to the list of applications in `:applications` in mix.exs.

**Comment by refriedchicken** [comment]
crap you are right, I am sorry about that new to elixir and missed that.

**Comment by mabeebam** [comment]
Hi @ericmj,

I stumbled over the same problem! Created a PR #44 to improve usage instructions.

Cheers
