### ISSUE TITLE
Easy way to convert BSON.ObjectId to String?

### ISSUE THREAD

**Issue by amokan** [elixir-mongo/mongodb#40]
I'm sure I may be missing something here, but after an insert I get back a `BSON.ObjectId` like `#BSON.ObjectId<1e0b239999a1014ed1b35a84>`.

What is the easiest way to get a string representation of the actual `_id` for later use?

I've tried something like `%BSON.ObjectId{value: object_id} = #BSON.ObjectId<1e0b239999a1014ed1b35a84>`, but then I have a binary.

Feels like I'm missing something real simple here. Thanks!

**Comment by hectorip** [comment]
The "actual" _id you should use to compare and make queries is the BSON.ObejectId you already have, but if anyways you want a string representation of the value in the ObjectId you could get it in this way:

``` elixir
string_object_id = Base.encode16(obejct_id.value, case: :lower)
```

**Comment by amokan** [comment]
@hectorip Thanks! Exactly what I was looking for.

**Comment by edgurgel** [comment]
It should be easy to make `to_string/1` work with object ids right? Implementing the `String.Chars` protocol, right?

**Comment by hectorip** [comment]
@edgurgel I'm not that advanced in Elixir still don't know how to work with protocols :( but I would like to see how you implement that(If you plan to do so) :+1:

**Comment by edgurgel** [comment]
Sorry for the super delay!

Here's what I did on my project:

``` elixir
defimpl String.Chars, for: BSON.ObjectId do
  def to_string(object_id), do: Base.encode16(object_id.value, case: :lower)
end
```

```
iex(1)> Mongo.IdServer.new |> to_string
"56ea0661b018c92fe0f32c1e"
```

I would send a PR if @ericmj would like to have it so people can easily `to_string` it.

**Comment by ericmj** [comment]
Go ahead.

**Comment by michalmuskala** [comment]
We already have `BSON.ObjectId.encode!/1` and `BSON.ObjectId.decode!/1` to convert between struct and string representation.

I'm not sure `BSON.ObjectId` should implement `String.Chars` protocol, because it's not strictly a string or string-like data.

**Comment by edgurgel** [comment]
@michalmuskala, that's a good argument but as a current user of mongo I would say that it's pretty common to use mongo object ids to interact with other databases and usually the string representation is used so it's also readable. 

I'm ok if this should not be part of the project as it's super simple to add on my projects. 

I would like to add also that inspect is already provided with similar approach so I don't think it would be harmful to provide a string representation as well.

**Comment by tomjoro** [comment]
In older versions of MongoDB there was no reference type for BSON.ObjectId, so you had to store references _id's to other collections as strings. I still have some Dbs in production like that. Also, if you serialize to JSON to use id's (like with an SPA) and synchronize.

**Comment by fidellr** [comment]
is there any differences with this way:

`
strArticleID := bson.ObjectId(articleID).Hex()
`?
i used to do with this, any suggestions?

**Comment by ankhers** [comment]
@fidellr I just want to make sure I understand. That looks like golang code. This is the Elixir driver for Mongo. Are you interested in the Elixir equivalent of that golang code? Or did you end up on the wrong repository?
