### ISSUE TITLE
GenServer Timeout

### ISSUE THREAD

**Issue by hectorip** [elixir-mongo/mongodb#41]
Hi @ericmj! I have been recently working with massive datasets and more or less complex aggregate functions to retrieve data, operations that sometimes last 2-3 minutes. I've set the HTTP timeout high but even with this option if my process lasts more than five secs the GenServer.call raises an exception because it is always called with the default timeout for GenServer operations(5000ms), do you think is worth to send the same time as in HTTP timeout for mongo? For the moment I have this in my local project:

``` elixir
GenServer.call(conn, {:find, coll, query, select, opts}, 60_000)
```

`60_000` is a hardcoded limit I put only to try, and it worked.

**Comment by ericmj** [comment]
Don't know what HTTP timeout you are referring to but we can add a `:timeout` option to all functions calling the connection.
