### ISSUE TITLE
Is there anyway I can specify a clean connection without a database setting?

### ISSUE THREAD

**Issue by eminarcissus** [elixir-mongo/mongodb#42]
Currently I'm migrating a lib which using elixir-mongo as dependency which it doesn't require a database when creating a connection(which should be much more nature as well). The reason why I'm doing so is because elixir-mongo did purge all values's key into atom which might cause a huge memory leakage if it is running in a long term,and looks like their project is unmaintained for a while as well.

Everything looks fine for mongoldb as well, but I can't find anyway to create a clean connection to the database both with Mongo.Connection or MongoPool, is there any way I can circumvent with this restricts.

And also I did notice all find/update or db actions are taking collection as the first argument, so from my understanding this is a designed pattern, but indeed I need to maintain a single connection and talks to multiple db in the same time, is there anyway I can use it except for fork a new version?

**Comment by ericmj** [comment]
You can specify any database name, the database should only be created if you persist something to it and it won't error if the database doesn't exist.

> And also I did notice all find/update or db actions are taking collection as the first argument, so from my understanding this is a designed pattern, but indeed I need to maintain a single connection and talks to multiple db in the same time, is there anyway I can use it except for fork a new version?

I don't fully understand this but it sounds like you want to use a single connection for multiple databases? That is not supported currently but can be added quite easily.

**Comment by eminarcissus** [comment]
Thx, that would be really helpful.
Yes, I want a single connection(or a pool) to be able to talk to multiple database, or to be more specifically want a additional argument when doing CRUD actions, like opts[:database] to change the db it in default talks to.

**Comment by tomjoro** [comment]
Can't you do it like this? I don't see any advantage of using a single connection. The mongo requests are scoped on a connection anyways.

```
defmodule PoolOne do
  use Mongo.Pool, name: __MODULE__, adapter: Mongo.Pool.Poolboy
end
{:ok, _} = MongoPool.start_link(database: "dbone")

defmodule PoolTwo do
  use Mongo.Pool, name: __MODULE__, adapter: Mongo.Pool.Poolboy
end
{:ok, _} = MongoPool.start_link(database: "dbtwo")

Mongo.insert_one(PoolOne, "test-collection", %{"field" => 10})
Mongo.insert_one(PoolTwo, "test-collection", %{"field" => 10})
```

**Comment by eminarcissus** [comment]
Yes that works, but it makes me have to create a one more repo(pool) before talking to the second DB, but indeed in prod environment I have quite a few of them and all connections are created dynamically. That make the code looks really weird, because connection are connects between client and db, not talk to specific database in any lib. So specify a database when doing CRUD looks more natural to me. I would love to see such features available.

**Comment by ericmj** [comment]
@eminarcissus Please open an issue for that.

**Comment by MarkNijhof** [comment]
Hi,

I have the same problem, our solution can has an unspecified (I know at run time, but not at compile time) number of mongo databases that each need to be accessed individually. How could I make this dynamic so I don't have to specify PoolOne and PoolTwo but perhaps can say something like Pool.get("One") and Pool.get("Two"). Or can I create a GenServer that starts as many pools as needed, making the name: the same as the database. Then ask this GenServer for the right PID and use that instead of the PoolOne or PoolTwo in the insert_one statement?

What is the suggested way forward on this?

**Comment by ericmj** [comment]
The changes here https://github.com/ericmj/mongodb/pull/52 will provide a `start_link` function you can use for that.
