### ISSUE TITLE
Add database option support for CRUD functions

### ISSUE THREAD

**Issue by eminarcissus** [elixir-mongo/mongodb#43]
distinct/find/insert_one/insert_many/delete_one/delete_many/replace_one/update_one/update_many/save_one/save_many including MongoCursors should support :database option to specify a database to talk with.

**Comment by chowevtfy** [comment]
I'm going to be adding this as part of #69

**Comment by chowevtfy** [comment]
See #79

**Comment by ghost** [comment]
This is still part of #93 btw.
