### ISSUE TITLE
Query by ObjectID hexadecimal string

### ISSUE THREAD

**Issue by adrian-catana** [elixir-mongo/mongodb#45]
How can I query for document based on ObjectID as string? The only way I could get it to work is
to use Mongo.Ecto.ObjectID.dump from Mongo.Ecto project, like this:

`Mongo.find(MongoPool, "some_collection", %{_id: elem(Mongo.Ecto.ObjectID.dump("55e724bf44f4173c876919f9"),1) })`

is there a way to do it and not depend on an external project?

**Comment by michalmuskala** [comment]
I think a helper function for this directly in Mongo could be useful.

**Comment by ericmj** [comment]
We can add encode and decode functions to `ObjectId`.
