### ISSUE TITLE
JSON encoding

### ISSUE THREAD

**Issue by travisjeffery** [elixir-mongo/mongodb#46]
Would be useful to encode to JSON, e.g. map of strings:

```
BSON.encode_json(doc)
%{"_id" => "559c3c676b92c9bf5c0898fd", "name" => "Travis"}
```

I'm pretty new to Elixir and this is above my level still, but when I can do it I'll make a PR if there isn't already.

**Comment by ericmj** [comment]
You can use a JSON library for that, for example https://github.com/devinus/poison.

**Comment by travisjeffery** [comment]
Right but even then you have to the hardwork of re-encoding them yourself: https://github.com/devinus/poison/issues/66#issuecomment-179187201.

**Comment by ericmj** [comment]
If you are using master of this library you can implement the protocol for ids:

``` elixir
defimpl Poison.Encoder, for: BSON.ObjectId do
  def encode(id), do: BSON.ObjectId.encode(id)
end
```

**Comment by travisjeffery** [comment]
Ah nice!

Here's the implementation in case anyone else hits this:

``` elixir
defimpl Poison.Encoder, for: BSON.ObjectId do
  def encode(id, options) do
    BSON.ObjectId.encode!(id) |> Poison.Encoder.encode(options)
  end
end
```

Thanks!

**Comment by beno** [comment]
Where do I add this code? When I try it in various places I always get:

```
warning: the Poison.Encoder protocol has already been consolidated, an implementation for BSON.ObjectId has no effect
```

I don't reference Poison.Encoder anywhere else.

**Comment by ericmj** [comment]
@beno Anywhere in your Elixir files under the `lib/` directory.

**Comment by beno** [comment]
But then I run into the above warning and the code indeed has no effect.

**Comment by ericmj** [comment]
If you get that warning you have some other issue with your project since you should not get it. If you have some way to share your project I can take a look at it.

**Comment by beno** [comment]
When I create a new mix app, with 2 dependencies (poison and mongoldb) and just the code above in lib I run into this issue. But interestingly only when I type `recompile` at the iex prompt, not when I do a full quit/start cycle.

I got confused here, because the initial compile also gives a warning:

```
warning: function BSON.ObjectId.encode!/1 is undefined or private
```

So the code above is not valid out of the box. Can you please shed some light on this?

**Comment by ericmj** [comment]
The `recompile` issue was a bug in Elixir. Update and it should be fixed.

`BSON.ObjectId.encode!/1` is only available on the master branch so far.

**Comment by beno** [comment]
I was on Elixir 1.3.1, have just now updated to Elixir 1.3.2 but the consolidated protocol warning remains.

@ericmj here is a repo which produces the error https://github.com/beno/consolidate_error

**Comment by ericmj** [comment]
@beno Please open an issue on the Elixir project if the warning is still happening.

**Comment by beno** [comment]
Allright, done https://github.com/elixir-lang/elixir/issues/5228
