### ISSUE TITLE
Issue with BSON decoder and ObjectId

### ISSUE THREAD

**Issue by blacksails** [elixir-mongo/mongodb#48]
I get an error when the BSON decoder tries to decode the machine identifier bytes of an ObjectId.

```
** (MatchError) no match of right hand side value: <<111, 230, 80, 74, 154, 74, 223, 8>>
stacktrace:
  (mongodb) lib/bson/decoder.ex:98: BSON.Decoder.document/1
  (mongodb) lib/bson/decoder.ex:6: BSON.Decoder.decode/1
  test/controllers/user_controller_test.exs:27
```

The original binary was <<86, 206, 224, 104, 111, 230, 80, 74, 154, 74, 223, 8>>

**Comment by blacksails** [comment]
I changed to using mongodb directly from github, and then I use BSON.ObjectId.encode! and BSON.ObjectId.decode! instead of the functions found in the BSON module, then it works.

Is there a better way of doing that, or is that just how it is at the moment?

**Comment by ericmj** [comment]
The functions in the BSON module encode to and from the BSON format, you should usually not call these functions yourself because the driver does it for you. BSON.ObjectId converts an ObjectId struct to and from its hex representation.

**Comment by ericmj** [comment]
> Is there a better way of doing that, or is that just how it is at the moment?

What do you mean?

**Comment by ericmj** [comment]
Closing this due to no response.
