### ISSUE TITLE
Add support for NaN and +/-Inf

### ISSUE THREAD

**Issue by lewtds** [elixir-mongo/mongodb#50]
Elixir (and Erlang) doesn't natively support those special floating point values so if we see any such value from Mongo, we'll simply throw up an error.

```
        ** (FunctionClauseError) no function clause matching in BSON.Decoder.type/2
            (mongodb) lib/bson/decoder.ex:10: BSON.Decoder.type(1, <<0, 0, 0, 0, 0, 0, 248, 127>>)
```

It might be possible to binary match to detect those values and return our own special atoms as discussed here: https://groups.google.com/forum/#!topic/capnproto/T6jEFu38rtI

and here: https://github.com/kaos/ecapnp/commit/a4e32216a650ccebef1122ea150384f0a4939295#diff-d28a6e8472db5dc7149ae3347d12566aR84

**Comment by ericmj** [comment]
A PR would be appreciated. You can look at https://github.com/ericmj/postgrex/blob/master/lib/postgrex/extensions/float8.ex for inspiration on how to handle the special atoms.

**Comment by TreyE** [comment]
This bit me the other day, I did binary match for these special values, before I remembered the dreaded issue of erlang/elixir not having native NaN +/- Inf support.  I saw the example on how to handle the special atoms and it works good for encode, the question I think is what is a well-behaved and sane interface to use when decoding?

Resorting to an atom seems kind strange to me - this can't be a problem nobody else in the elixir community has ever grappled with - is there a standard pattern that the authors of other libraries have used?

**Comment by ericmj** [comment]
> For a fix for this, is there a standard pattern that the authors of other libraries have used?

Yes, see the link to postgrex above.

**Comment by TreyE** [comment]
I don't know of a better solution, but I think what has me feeling strange about usage of an atom is that it will cause guard clauses on type to fail.  Would we deal with this by updating typespecs to include the possibility of an atom so maybe this can be caught when people dialyze projects?

I.E. should we treat this kind of like how the maybe monad propagates through code in haskell?

**Comment by ericmj** [comment]
You could add the atoms to this typespec: https://github.com/ericmj/mongodb/blob/master/lib/bson.ex#L6  but it already covers all atoms.

**Comment by TreyE** [comment]
Ah, I see.  Since the actual types in the wild a decoded BSON document is capable of having are already non-deterministic enough:
1. it's already covered by the typespecs you've chosen
2. it's really the responsibility of the client (in this case the consumer of the decoded document) to deal with/know what its document structure is supposed to look like anyway

Would this mean that adding +/- Inf and Nan as possible values returned from a decoded float only really needs an update to the documentation (aside from the obvious decoding/encoding implementation), and is still consistent with the API you've already designed?

**Comment by TreyE** [comment]
Even though the PR #56 has been accepted, I would recommend keeping this ticket open until PR #63 is merged in as well, given that it seems my implementation used the wrong endianness.

**Comment by henry-hz** [comment]
:+1:
