### ISSUE TITLE
:get_more timeout error

### ISSUE THREAD

**Issue by adrian-catana** [elixir-mongo/mongodb#53]
If I run a Mongo.find query on a large mongo collection in a busy server with:

```
cursor = Mongo.find(MongoPool, "userdata", %{state: "ready"}, batch_size: 1000)
```

After a few hours of running I always get a timeout into :get_more:

```
** (exit) exited in: GenServer.call(#PID<0.169.0>, {:get_more, "userdata", 17595059170, [batch_size: 1000]}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:564: GenServer.call/3
    (stdlib) timer.erl:181: :timer.tc/2
    lib/mongo/pool/poolboy.ex:36: Mongo.Pool.Poolboy.run/2
    lib/mongo/pool.ex:142: Mongo.Pool.run_with_log/5
    lib/mongo/cursor.ex:65: anonymous fn/3 in Enumerable.Mongo.Cursor.next_fun/2
    (elixir) lib/stream.ex:1099: Stream.do_resource/5
    (elixir) lib/enum.ex:1477: Enum.reduce/3
    (elixir) lib/enum.ex:1092: Enum.map/2
```

The :timeout connection parameter is not used for :get_more so the only way to fix it is to manually edit this line: https://github.com/ericmj/mongodb/blob/943f6bcefff916e2e8b572fad1c9d79d55235490/lib/mongo/connection.ex#L64

and change it to:

```
GenServer.call(conn, {:get_more, coll, cursor_id, opts}, 50000)
```

With 50000 everything works fine and I no longer get any timeouts. So I think the :timeout connection parameter should also be use here or maybe create a new parameter.

**Comment by ericmj** [comment]
This has been fixed in the db_connection rewrite.
