### ISSUE TITLE
Monitoring tailable cursor events

### ISSUE THREAD

**Issue by ghost** [elixir-mongo/mongodb#55]
So, if you create a tailable cursor, you can use the cursor as a Stream; however, the functionality that a tailable cursor adds (allowing you to see newly inserted documents for a cursor as they are added) doesn't really support streams. We'd need some way to have a supervised process that sends new results to another process as they are available. Here's the code for how RethinkDB handles this:

https://github.com/hamiltop/rethinkdb_changefeed

**Comment by ericmj** [comment]
Not sure what you mean. Why can't you handle this in the process that is running the stream?

**Comment by ghost** [comment]
The problem is that no process can always be running the cursor stream, since we have to close the cursor eventually. Once you try to run the stream a second time, all the results are returned, not just the new ones, probably because a new cursor was created after the last one was closed. So somehow, we have to keep the cursor from closing (and therefore the stream as well) when using a `:tailable` cursor as a stream. I noticed that this happens for a very short period of time if you use a `:tailable_await` cursor, but it needs to happen indefinitely.

**Comment by ericmj** [comment]
In that case it sounds like the streaming cursors needs to better support tailable queries to ensure they do not close prematurely. I do not understand why we would a second supervised process.

**Comment by ghost** [comment]
It doesn't necessarily need a second supervised process, it just needs the current supervised process to send new results to a process as they become available from a tailable cursor somehow.

**Comment by ericmj** [comment]
That's something you can easily build yourself. I still don't know why you even need the second process. The nice thing with streams is that you get automatic back pressure. When you start sending messages you run the risk of sending faster than you can handle the messages.

**Comment by ghost** [comment]
If you think of each item coming from the cursor as a message, then you can process messages synchronously just fine, until there's a large break where you need to wait for more messages. Sure, it accounts for back-pressure well when using them synchronously, but it _doesn't work_ when you have to wait a long time for new messages. I don't want to buffer messages either, since I want them as soon as they happen. Streamable cursors don't currently give you the ability to wait a long time for new messages. This is a potential use of tailable cursors not possible with the library as it is now, and adding that capability is the purpose of this issue.

To be perfectly clear, here's an example with the Ruby driver:

```
db = Mongo::Connection.new().db('my_db')
coll = db.collection('my_collection')
cursor = Mongo::Cursor.new(coll, :tailable => true)
loop do
  if doc = cursor.next_document
    puts doc
  else
    # Elixir client is currently hardcoded to close the cursor and break here
    # since sleep isn't encouraged in Elixir, we should use messages for asynchronous notification instead
    # Ruby lets me sleep here and wait for new documents
    sleep 1
  end
end
```

**Comment by ericmj** [comment]
> Streamable cursors don't currently give you the ability to wait a long time for new messages.

Why not? Can you point me to the actual issue?

**Comment by ghost** [comment]
Yes, I will just submit a PR to be perfectly clear.

**Comment by ericmj** [comment]
Closing this issue in the meantime since it's not actionable by me.

**Comment by ghost** [comment]
To be specific, here's the exact violation of the specification that this bug refers to:

```
enum CursorType {
[...]
  /**
   * Tailable means the cursor is not closed when the last data is retrieved.
   * Rather, the cursor marks the final object’s position. You can resume
   * using the cursor later, from where it was located, if more data were
   * received. Like any “latent cursor”, the cursor may become invalid at
   * some point (CursorNotFound) – for example if the final object it
   * references were deleted.
   *
   * @see http://docs.mongodb.org/meta-driver/latest/legacy/mongodb-wire-protocol/#op-query
   */
  TAILABLE,
[...]
}
```

https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#read

The specific violation is that the cursor _is_ closed when the last data is retrieved, which is apparent from the implementation of the stream.

Here is the line of code that demonstrates that violation:

https://github.com/ericmj/mongodb/blob/master/lib/mongo/cursor.ex#L71

**Comment by ericmj** [comment]
Okay, now I understand better. If you would like to send a PR, please do it against the new branch: https://github.com/ericmj/mongodb/tree/emj-dbconn.

**Comment by BogdanHabic** [comment]
@ericmj Whats the status on this issue (I cannot find anything regarding this on the https://github.com/ericmj/mongodb/tree/emj-dbconn branch).

If @cjhowe doesn't/didn't take this upon himself to implement it, I would be glad to do it. 😄

**Comment by ghost** [comment]
Actually, I just tested fixing it today! A PR is on the way.

**Comment by chowevtfy** [comment]
See #79

**Comment by BogdanHabic** [comment]
Sorry, I don't know how I missed it.
Ok, this is great news to hear. ;)
