### ISSUE TITLE
Intermittent test failures in test/mongo/connection_test.exs

### ISSUE THREAD

**Issue by TreyE** [elixir-mongo/mongodb#57]
It seems there are intermittent failures in the test/mongo/connection_test.exs file, for the "auth wrong" scenario on line 31.

As an example travis run:
https://travis-ci.org/ericmj/mongodb/jobs/141147103

Is it possible this is the kind of message ordering issue that should be handled using special process tests, as described here:
http://blog.carbonfive.com/2016/06/28/special-processes-in-otp/ ?

**Comment by ericmj** [comment]
I don't know. Could be just be a timeout issue where travis is low. Can you reproduce this locally?

EDIT: Also, can you reproduce it on https://github.com/ericmj/mongodb/pull/52?
