### ISSUE TITLE
Using with a database connection string

### ISSUE THREAD

**Issue by michaelforrest** [elixir-mongo/mongodb#60]
I want to use this on Heroku where I am provided a full connection string as an environment variable. Is there any way to connect with a string in the following format?

`mongodb://heroku_****:****@***.mlab.com:17545,***.mlab.com:17545/heroku_*****?replicaSet=rs-****`

**Comment by ericmj** [comment]
No, that is unfortunately not supported currently. A PR would be appreciated.

**Comment by michaelforrest** [comment]
I'd love to provide a pull request but I fear I am a little out of my depth writing this! Could you give me some ideas on where / how to implement this? I'm looking at adding a test to `connection_test.ex` and the implementation as part of `Connection.connect/2`? But it seems to be using `:gen_tcp.connect` rather than anything Mongodb-looking, and I don't really know how that would work, especially where my url has two hosts specified and this `replicaSet` option.

**Comment by ericmj** [comment]
You would have to parse the URL and extract hostname, port, usernname and password. Then pass in those parameters where necessary.

This driver does not support replica sets.

**Comment by AdamBrodzinski** [comment]
@ericmj Is this something that you would still be interested in? I might be able to do a PR over the next few weeks or so.

Currently I have a crude regex in my config to extract a Mongo URI (below) but I could clean it up and support the optional/default values as well.

```elixir
[[_full, user, pass, host, port_str, db_name]] = Regex.scan(~r/mongodb\:\/\/(.+)\:(.+)\@(.+)\:(\d+)\/([\w-]+)/, System.get_env("MONGO_URL"))

config :data, Mongo,
  name: :mongo,
  database: db_name,
  hostname: host,
  username: user,
  password: pass,
  port: String.to_integer(port_str),
  pool: DBConnection.Poolboy
```

**Comment by ericmj** [comment]
@AdamBrodzinski we have similar functionality in Ecto using `URI.parse/1`. I would suggest taking a look at that.
