### ISSUE TITLE
How to create a BSON DateTime struct?

### ISSUE THREAD

**Issue by tastywheat** [elixir-mongo/mongodb#65]
Hi there, I'm an elixir noob trying to insert a date into mongo, but I can't figure out to to create the BSON.DateTime object properly. I'm currently doing this:

```
utc = :calendar.datetime_to_gregorian_seconds(:calendar.universal_time)
%BSON.DateTime{utc: get_utc_timestamp}
```

When it saves to mongo, it shows up as `1972-01-07...`.

What's the correct way to create a DateTime for `now`?

**Comment by ericmj** [comment]
It should be UTC milliseconds since Unix epoch. You can use this function: http://elixir-lang.org/docs/master/elixir/DateTime.html#to_unix/2.
