### ISSUE TITLE
Move BSON to a separate lib

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-mongo/mongodb#68]
Hi,

I want to suggest you to move BSON lib to a separate HEX package, since your implementation works _much_ (more than 50%) faster and predictable than `bson` package that have 10k downloads right now.

At the moment I'm used to copy-paste your code and make some cleanup, since making DB driver as dependency to parse BSON would be an ugly solution.

**Comment by AndrewDryga** [comment]
Project where I need it is located here: https://github.com/Nebo15/bsoneach

**Comment by ericmj** [comment]
I currently have no plans to extract a bson package. Maybe you can help improving the existing bson package with the code from this library. Then this library can also use the bson package as dependency eventually.
