### ISSUE TITLE
How to catch/rescue errors?

### ISSUE THREAD

**Issue by tastywheat** [elixir-mongo/mongodb#72]
The code below would throw a duplicate ID error, but the rescue doesn't work.
What's the right way to catch/rescue an operation so that I can log the message?

```
try do
  Mongo.insert_one(MongoPool, "articles",%{"_id" => "aaa"})
  Mongo.insert_one(MongoPool, "articles",%{"_id" => "aaa"})
rescue
  e in RuntimeError -> IO.inspect e
end
```

**Comment by ericmj** [comment]
You should rescue the specific error that is raised from the function. I believe it is `Mongo.Error`.
