### ISSUE TITLE
After insert_one BSON Object is Returned

### ISSUE THREAD

**Issue by andrewcottage** [elixir-mongo/mongodb#85]
After I insert some data I get this:

```
%Mongo.InsertOneResult{inserted_id: #BSON.ObjectId<57dc602dfa2d310e03f95be8>}
```

That's great, but I have no idea what to do with this `BSON.Objectid` I would like to get back maybe a map of all the data I just inserted or the Mongo ID so I can look up the record I just inserted.

Can anyone help me figure out how to do this?

**Comment by ericmj** [comment]
There is no such thing as a "Mongo ID". What you need to look up the record is the `BSON.ObjectId` that is returned.

**Comment by andrewcottage** [comment]
Thank You! This was just due to my inexperience with Mongo.
