### ISSUE TITLE
protocol Enumerable not implemented for %Mongo.Cursor

### ISSUE THREAD

**Issue by rockerBOO** [elixir-mongo/mongodb#9]
Hi there. Thanks for this great library! I have been struggling with a few other libraries that are basically dead. Everything works as expected until this issue came up. I can't figure out how to get past it, and using the code for `find` that you're using in the tests. I understand this is basically pre-alpha, but my requirements are limited at the moment.

``` elixir
  defmodule MongoPool do
    use Mongo.Pool, name: __MODULE__, adapter: Mongo.Pool.Poolboy
  end

collection = "broadcasts0"
Mongo.find(MongoPool, collection, %{} |> Enum.to_list
```

``` elixir
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for %Mongo.Cursor{coll: "broadcasts-0", opts: [], pool: MongoPool, query: %{}, select: nil}
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:112: Enumerable.reduce/3
        (elixir) lib/enum.ex:1265: Enum.reduce/3
        (elixir) lib/enum.ex:1807: Enum.to_list/1
```

Thanks :smiley:

**Comment by ericmj** [comment]
That is very weird because we have a test that covers this: https://github.com/ericmj/mongodb/blob/master/test/mongo_test.exs#L74-L75. Try to refetch and recompile the dependency.

**Comment by rockerBOO** [comment]
I cleared out cleared out all the mix related items, including mix.exs :astonished:. Fixed the mix.exs and it WORKED :+1: 

Apparently there is some lingering files I am not aware of being added in with the mix stuff.

**Comment by gVolop** [comment]
same issue :(
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for %Mongo.Cursor{coll: "collection1", opts: [], pool: MongoPool, query: %{}, select: %{}}
     (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
     (elixir) lib/enum.ex:146: Enumerable.count/1
     (elixir) lib/enum.ex:2695: Enum.enumerable_and_count/2
     (elixir) lib/enum.ex:2006: Enum.slice/2
    (invoice) lib/rates.ex:37: Invoice.Rates.update_rates/3
```
