### ISSUE TITLE
Version 3.4

### ISSUE THREAD

**Issue by mandado** [elixir-mongo/mongodb#97]
Will version 3.4 be supported?

**Comment by ericmj** [comment]
What errors are you seeing with 3.4?

**Comment by mandado** [comment]
I have not tested it yet, it's just a question.

**Comment by edgesoft** [comment]
@mandado Yes, version 3.4 is supported

**Comment by edgurgel** [comment]
The README has a section where it outlines the supported versions: https://github.com/ericmj/mongodb#features
